### PR TITLE
fix: Do not scan quest book on entering world

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Forgot to add the reasoning. Basically, we do not depend on the quest book analysis anywhere expect the quest book screens itself, where we are free to do analysis. Scanning on world join is useless therefore.

**Review by Incompleteusern — APPROVED** [review]

**Comment by magicus** [comment]
My reason for adding it was to do it in the "background" when you logged in, to make the quest book gui come up more snappy. But maybe the container query is so efficient that is not a problem?

**Comment by kristofbolyai** [comment]
> My reason for adding it was to do it in the "background" when you logged in, to make the quest book gui come up more snappy. But maybe the container query is so efficient that is not a problem?

Wynn is slow, so this blocked interactions for a few seconds on world join.

**Comment by magicus** [comment]
But otoh, now there will be once again a delay when opening the Wynntils quest book? Oh well, I guess it's better than freezing your character when you log in. (I never noticed this, though, but I agree that this sounds like a worse problem, if it happens)

**Comment by kristofbolyai** [comment]
> But otoh, now there will be once again a delay when opening the Wynntils quest book? Oh well, I guess it's better than freezing your character when you log in. (I never noticed this, though, but I agree that this sounds like a worse problem, if it happens)

Yeah, okay conpromise

**Pull request merged**
