### PR TITLE
fix: Restore GUI scale after reloading options

### LINKED ISSUE #2816: GUI scale does not retain its last value when starting in windowed
What version of the mod are you using? Please include a full version number.
V2.1.1
    What mod loader did you use?
Fabric loader 0.16.2-1.21.1
    Did you use any other mods?
No
    What operating system are you using?
Windows 10
    What did you do?
Start Minecraft
    What did you expect to see?
GUI scale: 3 (because that was what it was last time)
    What did you see instead?
GUI scale: 2

The setting video settings-> gui scale should retain the value it had last time on startup. It does not and always reverts back to 2 even though I set it to 3 last time I closed minecraft. My guess is that windowed mode resets the GUI scale to 2 (only with this mod). When starting minecraft with only fabric installed this issue does not exist.

### PR DESCRIPTION
**Pull request by CommandMC**
Closes #2816

This fix is rather crude, but sadly it's the best solution I've found. Another option would be to re-implement part of the options loading method, but that seemed very fragile to me.

### CODE REVIEW

**Review by kristofbolyai — COMMENTED** [review]
I don't think this is actually too hacky. In fact, I would have already coded this, but I talked about it to @ShadowCat117 and they said they've already tried this. Did you try this, or did we talk about different solutions? If you tried this, we need to spend a bit of time figuring out whether this works for everyone, every launcher and whether it is stable enough.

**Comment by CommandMC** [comment]
I tested this both on my normal Wynncraft instance (using just about every mod listed in Launchy, although updated to 1.21) and on Vanilla (with just Wynntils & Fabric loader).

It's important to set the `value` member of the `OptionInstance` here directly, as using the `set` method validates the value (which ends up clamping it down again). Maybe that was the issue last time?

I'm actually surprised it works this well, as setting `value` directly also skips calling `OptionInstance.onValueUpdate`, meaning we don't call `Minecraft.resizeDisplay()` to resize the render target.

**Comment by ShadowCat117** [comment]
I thought this is how I did it before but I suppose not if this works

**Review by kristofbolyai — APPROVED** [review]
Essentially, I think the idea is good, I would have done the same thing. It seems to work in-game as well. Let's merge it, and see if any issues pop up. Thank you.

**Pull request merged**
