### PR TITLE
fix: Remove use of @Redirect in mixins

### PR DESCRIPTION
**Pull request by magicus**
This is almost all instances of @Redirect. Some command stuff is trickier and remains to be fixed.

Also contains some related mixin cleanups, like renaming our injected fields to always start with `wynntils` to avoid mod collisions.

### CODE REVIEW

**Comment by magicus** [comment]
Verified with Fabric and Forge.

**Comment by kristofbolyai** [comment]
> Also contains some related mixin cleanups, like renaming our injected fields to always start with `wynntils` to avoid mod collisions.

https://gist.github.com/apple502j/48883911bffc4b10bc2975335f2fd5d5#mixin-0123. As a heads up, in the future, there won't be a need for this. (But we still "need" this for current loader versions, many people won't use the new loader for 1.19.3 if not forced to.)

**Review by kristofbolyai — APPROVED** [review]
We should use beta 4 of MixinExtras.

**Comment by magicus** [comment]
> We should use beta 4 of MixinExtras.

Yes. Feel free to update. :)

**Pull request merged**
