### PR TITLE
fix: fix item detection (blacksmith selling)

### PR DESCRIPTION
**Pull request by ENORMOUZ**
Seems that Wynn does not put the reset colour code in front of items

### CODE REVIEW

**Comment by ENORMOUZ** [comment]
It appears that this fix does not work for Set and Fabled items (not testing Mythic and Crafted items because yeah), will try to fix

**Comment by ENORMOUZ** [comment]
Turns out it is because it does not recognise characters like (-) like in Morph-Stardust, (') like in Gale's Force coding a fix

**Comment by ENORMOUZ** [comment]
Now uses itemMatcher.lookingAt() instead of itemMatcher.matches() to hopefully account for all symbols and other stuff, should still be accurate with no false positives

**Comment by ENORMOUZ** [comment]
Will fix later

**Comment by magicus** [comment]
Can you describe what the problem is that you are trying to solve? Is it that items with anything but a-z in their names are not properly detected?

**Comment by ENORMOUZ** [comment]
> Can you describe what the problem is that you are trying to solve? Is it that items with anything but a-z in their names are not properly detected?

Items with "-" and "'" in their name are not detected, coding a fix but busy rn

**Comment by magicus** [comment]
I see you are struggling a bit with this. You can solve this issue by only updating the regexp. That is the proper solution, and the one one that can be accepted. So you need to tweak the regexp.

Try going to regex101.com, paste in the regex and a bunch of real-world strings from Wynncraft, and see so you can make it match.

**Review by magicus — APPROVED** [review]

**Pull request merged**
