### PR TITLE
feat: Make ItemScreenshotFeature disk saving optional

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by magicus** [comment]
I'm not sure I'm getting this. There is no problem with saving screenshots on mac. It's just saving to the clipboard that does not work.

**Comment by magicus** [comment]
I had as a mental todo item to have another look at this feature. I think it is three things baked into one:
* Save a screenshot to disk
* Make a clipboard copy of the image
* Make a clipboard copy of the chat encoding

It's kind of confusing. For starter, having a separate hotkey for just copying for chat would make sense, I think.

**Comment by kristofbolyai** [comment]
> I'm not sure I'm getting this. There is no problem with saving screenshots on mac. It's just saving to the clipboard that does not work.

The point is that people don't want to save item screenshots to disk unnecessarily.

**Review by magicus — APPROVED** [review]
I think we need to split this up into separate functionality in the future, but lets do this for now

**Pull request merged**
