### PR TITLE
[ci skip] fix: Fix TestRegex failing tests

### PR DESCRIPTION
**Pull request by kristofbolyai**
I am wondering if we should pass strings through StyledText, and test those against the patterns as well. We still have a lot of reset characters in these patterns, and 99% percent of them could be removed... However, I am not sure if it is worth the effort; if it works, don't fix it.

### CODE REVIEW

**Review by magicus — APPROVED** [review]
Did you just remove §r or did you check these with ingame strings?

**Comment by kristofbolyai** [comment]
> Did you just remove §r or did you check these with ingame strings?

I've checked if the regexes were updated during the StyledText migrations, and if the reset chars have a color after them (which was a change introduced by StyledText)

**Comment by magicus** [comment]
We should probably re-parse our strings, that is, take the constant strings in the tests, and pass them through `StyledText.fromString("test string).getString()` (or whatever it was called), and replace the literals with whatever comes out the other side. It's probably a quick hack to do that.

We only match on StyledText or stuff that has passed StyledText, but many of the strings here were copied from the game chat before the advent of StyledText.

**Comment by magicus** [comment]
I just did this:
```
diff --git a/fabric/src/test/java/TestRegex.java b/fabric/src/test/java/TestRegex.java
index 9f7243829..721862001 100644
--- a/fabric/src/test/java/TestRegex.java
+++ b/fabric/src/test/java/TestRegex.java
@@ -2,6 +2,7 @@
  * Copyright © Wynntils 2023.
  * This file is released under LGPLv3. See LICENSE for full license details.
  */
+import com.wynntils.core.text.StyledText;
 import com.wynntils.features.chat.GuildRankReplacementFeature;
 import com.wynntils.features.chat.MessageFilterFeature;
 import com.wynntils.features.redirects.ChatRedirectFeature;
@@ -78,12 +79,20 @@ public class TestRegex {
         }
 
         public void shouldMatch(String s) {
+            String ns = StyledText.fromString(s).getString();
+            if (!ns.equals(s)) {
+                System.out.println("MISMATCH: " + s);
+            }
             Assertions.assertTrue(
                     pattern.matcher(s).matches(),
                     "Regex failure: " + regexName + " should have matched " + s + ", but it did not.");
         }
 
         public void shouldNotMatch(String s) {
+            String ns = StyledText.fromString(s).getString();
+            if (!ns.equals(s)) {
+                System.out.println("MISMATCH: " + s);
+            }
             Assertions.assertFalse(
                     pattern.matcher(s).matches(),
                     "Regex failure: " + regexName + " should NOT have matched " + s + ", but it did.");
```

and I found a bunch of strings that should be updated...

**Comment by magicus** [comment]
I can't be bothered to fix it right now, though...

**Comment by kristofbolyai** [comment]
I assumed, since I've found more than a hundred reset characters overall..

**Pull request merged**
