### PR TITLE
feat: add stat filters

### PR DESCRIPTION
**Pull request by kristofbolyai**
This should mean we have a full set of filters now :)

### CODE REVIEW

**Comment by ShadowCat117** [comment]
They don't seem to work at all in the guides?

**Comment by kristofbolyai** [comment]
> They don't seem to work at all in the guides?

Hm that might be the case..

**Comment by kristofbolyai** [comment]
Fixed.

**Comment by ShadowCat117** [comment]
Still doesn't work for ingredients, only item guide.

Looks good other than that though

**Comment by kristofbolyai** [comment]
> Still doesn't work for ingredients, only item guide.
> 
> 
> 
> Looks good other than that though

Yeah, intentional atm

**Comment by ShadowCat117** [comment]
> Yeah, intentional atm

Ok, is that going to be added in a follow up pr? If so I'll approve this

**Comment by kristofbolyai** [comment]
> > Yeah, intentional atm
> 
> 
> 
> Ok, is that going to be added in a follow up pr? If so I'll approve this

Yeah perhaps, i'll check it out tomorrow

**Review by ShadowCat117 — APPROVED** [review]

**Review by ryanzhoudev — APPROVED** [review]

**Pull request merged**
