### PR TITLE
feat: Add command aliases feature

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Review by magicus — COMMENTED** [review]
Hm. I dunno. I mean, if this is a requested feature or so, I won't say no. But if feels a bit ... ad-hoc..?

I'm thinking either perhaps we should support a general method of shortening commands? Or we should shorten it by parts, that is, allow "guild" to become "gu" or "g", as an independent thing from shortening the guild sub commands.

I thought Wynncraft allowed a short form of some commands. But maybe these were excluded, so they are just added to keep up consistence?

**Comment by kristofbolyai** [comment]
> Hm. I dunno. I mean, if this is a requested feature or so, I won't say no. But if feels a bit ... ad-hoc..?
> 
> I'm thinking either perhaps we should support a general method of shortening commands? Or we should shorten it by parts, that is, allow "guild" to become "gu" or "g", as an independent thing from shortening the guild sub commands.
> 
> I thought Wynncraft allowed a short form of some commands. But maybe these were excluded, so they are just added to keep up consistence?

This is an actual "feature" in legacy too. Technically this can be used to create any kinds of command macros, not just shorten actual commands.

**Review by P0keDev — APPROVED** [review]
i would definitely be interested in expanding this feature further and allowing users to define new aliases via the config gui (in a later PR of course)

**Comment by kristofbolyai** [comment]
> i would definitely be interested in expanding this feature further and allowing users to define new aliases via the config gui (in a later PR of course)

All you have to do is implement a `ConfigOptionElement` and register it in `getWidgetFromConfigHolder`. Then the rest is just GUI work.

**Pull request merged**
