### PR TITLE
fix: Correct chat item encoding of spell cost IDs

### PR DESCRIPTION
**Pull request by P0keDev**
Updates chat item logic for our new handling of spell cost IDs, which was previously encoding "negative" values and breaking the decoding process

### CODE REVIEW

**Comment by kristofbolyai** [comment]
How backwards compatible is this?

**Comment by P0keDev** [comment]
In chat items to and from artemis and legacy, spell cost IDs will be shown as the incorrect value (and usually out of the actual range of the ID). This can't really be avoided until legacy gets updated for the spell cost changes too, but I will try to finish that today

**Comment by kristofbolyai** [comment]
> In chat items to and from artemis and legacy, spell cost IDs will be shown as the incorrect value (and usually out of the actual range of the ID). This can't really be avoided until legacy gets updated for the spell cost changes too, but I will try to finish that today 

So old/new artemis is incompatible too? I know we can't avoid this, I am just curious

**Review by kristofbolyai — APPROVED** [review]

**Comment by P0keDev** [comment]
> > In chat items to and from artemis and legacy, spell cost IDs will be shown as the incorrect value (and usually out of the actual range of the ID). This can't really be avoided until legacy gets updated for the spell cost changes too, but I will try to finish that today
> 
> So old/new artemis is incompatible too? I know we can't avoid this, I am just curious

If you mean before/after this specific commit, the chat item feature straight up wouldn't work at all on items with spell cost IDs until this fix. Artemis versions from before the spell cost ID changes at all would be the same as legacy

**Pull request merged**
