### PR TITLE
fix: Fix (Buffered)FontRenderer not calculating width/height correctly in every case [skip ci]

### PR DESCRIPTION
**Pull request by kristofbolyai**
I think this should be everything needed for #2860, but I couldn't test this just yet. Can you perhaps try this, @ILikePlayingGames?

### CODE REVIEW

**Comment by kristofbolyai** [comment]
From my testing, this seems to work. Anyone found anything, or can we merge this?

**Comment by ShadowCat117** [comment]
I'll give it a quick test

**Review by ShadowCat117 — APPROVED** [review]
Seems fine

**Comment by kristofbolyai** [comment]
Thanks!

**Comment by ILikePlayingGames** [comment]
> I think this should be everything needed for #2860, but I couldn't test this just yet. Can you perhaps try this, @ILikePlayingGames?

Thanks I’ll try to test it tonight

**Pull request merged**
