### PR TITLE
refactor: Rename BossBarModel to AbilityModel and move AnnihilationSunBar to WorldEventModel [skip ci]

### PR DESCRIPTION
**Pull request by ShadowCat117**
Completely forgot we can register bars from models.. (:

### CODE REVIEW

**Comment by magicus** [comment]
Why do we even have a BossBarModel? I was confused at first since it should be a handler. Which it is; we just also have a BossBarModel. Did we not find any better place to put these boss bars? Maybe we should try a bit harder.

**Comment by ShadowCat117** [comment]
Probably CharacterModel is a good place to put the current ones as that already has some class information and the bars in there are class related

**Comment by kristofbolyai** [comment]
> Probably CharacterModel is a good place to put the current ones as that already has some class information and the bars in there are class related

So, are you planning to do it here, or should we merge this as is?

**Comment by ShadowCat117** [comment]
Yeah I can do it here

**Comment by ShadowCat117** [comment]
Actually, the BossBarModel is already in the abilities package so will just rename it to AbilityModel

**Review by kristofbolyai — APPROVED** [review]

**Pull request merged**
