### PR TITLE
fix: incorrect 2.1 mission colors [skip ci]

### PR DESCRIPTION
**Pull request by Aruloci**
Wynncraft Wiki has incorrect colors for 2.1 missions. Adjusted to correct in game colors.

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
We order by color then by name? Hm, sure, sounds good. Thanks.

**Comment by magicus** [comment]
Seems a bit arbitrary. Alphabetical order on the enum type would be better.

**Comment by ShadowCat117** [comment]
The original mission pr ordered them by colour which is [how they are on the wiki](https://wynncraft.wiki.gg/wiki/Lootrunning#Missions) we can change it to just be alphabetical regardless of colour though

**Comment by kristofbolyai** [comment]
Let's just merge the fix, and we can reorder it if anyone is up to it.

**Pull request merged**
