### PR TITLE
fix: Fix discoveries not being queried when only showing undiscovered [skip ci]

### PR DESCRIPTION
**Pull request by ShadowCat117**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Does this fix anything? Afaik undiscovered stuff are resolved from the API (hence my design)?

**Comment by ShadowCat117** [comment]
If you have the filter set to only show undiscovered, it will never show anything as `reloadDiscoveries` will just get all false so it'll never query anything

**Comment by ShadowCat117** [comment]
Current release, pressing reload leaves it empty


With this fix, pressing reload shows the undiscovered

**Comment by kristofbolyai** [comment]
Oh, hm, I guess this doesn't work as I thought it does..

**Comment by kristofbolyai** [comment]
Probably it was changed when the content book was updated..

**Comment by ShadowCat117** [comment]
Yeah content book contains everything for discoveries, you just can't track secret ones so we get the location info from the wiki

**Pull request merged**
