### PR TITLE
Feature/soul point

### PR DESCRIPTION
**Pull request by PhoenixOrigin**
Soul point but updated branch as @magicus asked working on bolyai comment right now.

### CODE REVIEW

**Comment by magicus** [comment]
Something seems to have been messed up in git with the switch. I'll help you resolve it.

**Comment by PhoenixOrigin** [comment]
Ok, thanks

**Comment by magicus** [comment]
This got really, really messed up. I can't salvage it. Instead, do like this:

Go to https://gist.github.com/magicus/741d59f55ba87afed113c3919cbda338 and download the file as `sp.diff`

`git chechout main`

`git switch -c soulpoint-main`

`patch -p1 < sp.diff`

`git commit -a`

and push the new branch to github and create a new PR.

**Comment by magicus** [comment]
@PhoenixOrigin Actually, don't bother. I didn't notice bolyai's objections. He is right. This is a fool's mission. You can never get this to work.

**Comment by PhoenixOrigin** [comment]
Why?

**Comment by magicus** [comment]
Your assumption -- that you can get the time of the server this way -- is incorrect. The margins of error are so high that it just becomes unusable. I will close this PR now.

**Pull request closed without merging**
