### PR TITLE
feat: Add soulpoint subcommand and aliases for server commands, click-to-switch server texts, fix formatting issues, command no longer hands the game

### PR DESCRIPTION
**Pull request by kristofbolyai**
The timeouts were removed since the ServerListModel now automatically updates every 15 seconds, no need for the manual force updates now, and the running the command feels much faster now.

image
image
image

### CODE REVIEW

**Review by ShadowCat117 — APPROVED** [review]
Looks good, one thing I will note if you want to fix it here there's been a bug for a while if you just run `/servers info` without an argument it sends you back to the lobby, I'm not quite sure what causes it

**Comment by kristofbolyai** [comment]
> Looks good, one thing I will note if you want to fix it here there's been a bug for a while if you just run `/servers info` without an argument it sends you back to the lobby, I'm not quite sure what causes it

/servers is a Wynn command. So that, I guess.

**Comment by ShadowCat117** [comment]
> /servers is a Wynn command. So that, I guess.

Ahh that would do it

**Comment by kristofbolyai** [comment]
> > /servers is a Wynn command. So that, I guess.
> 
> Ahh that would do it

Fixed it anyways

**Comment by magicus** [comment]
The updating every 15 seconds, were that done before? I can't figure it out from this PR. (Also, are we caching results in Athena or polling Wynncraft every 15 second?)

**Comment by kristofbolyai** [comment]
> The updating every 15 seconds, were that done before? I can't figure it out from this PR. (Also, are we caching results in Athena or polling Wynncraft every 15 second?)

I recently introduced it, when I added a server uptime overlay. We use athena (for the better or for the worse, Athena performance is really bad recently..)

**Pull request merged**
