### PR TITLE
feat: Add guild bank redirector in ChatRedirectFeature

### PR DESCRIPTION
**Pull request by kristofbolyai**
image

### CODE REVIEW

**Review by ShadowCat117 — APPROVED** [review]
Great idea, this is a better solution than filtering the messages entirely or adding a specific chat tab

**Comment by kristofbolyai** [comment]
Ended up changing the color for community opinion:
https://i.imgur.com/GyyX8jD.png

**Comment by magicus** [comment]
As a side note, the Chat redirector has really outgrown itself as a feature. I think we should have a model (*) for this, were we can register the parsers. It is encoding a lot of "knowledge" about Wynncraft messages and what they mean.

(*) or maybe another Component; I'm not sure...

**Comment by kristofbolyai** [comment]
Probably the extension of existing chat types in some ways.

**Pull request merged**
