### PR TITLE
QuestManager: Add coloring to quest description

### PR DESCRIPTION
**Pull request by kristofbolyai**
image

### CODE REVIEW

**Comment by magicus** [comment]
There is some kind of similar formatting in the original text. It is not simpler to try and keep it?

(Otherwise, please adjust the magenta coordinate color. It sticks out too much.)

**Comment by kristofbolyai** [comment]
What color do you recommend?

**Comment by magicus** [comment]
I dunno. Cyan? Yellow? What is the color used by Wynncraft?

**Comment by magicus** [comment]
Or leave it be for now. I think we need to do a "color overhaul" when we've come a bit further. Sometimes it looks a bit too much like a child's coloring book. :)

Or. We could have color profiles. That'd actually be cool. So we define a few "kinds" of highlights, like "general highlight", "coordinates", "names" etc, and we can have themes with nicely tuned colors for these.

**Comment by kristofbolyai** [comment]
image

**Comment by HighCrit** [comment]
In Wynntils we highlight coordinates in the same color as the items in the example. But we could make the color an option

**Comment by kristofbolyai** [comment]
I think they should have separate colors. Making it an option is a bit messy before we do the InternalFeature refactoring.

**Comment by magicus** [comment]
I agree that they should have different colors. The new screenshot looks nice. Is this using wynn colors but with coordinates changed to aqua (from white) and general text changed from gray to white?

**Review by magicus — APPROVED** [review]

**Comment by kristofbolyai** [comment]
> I agree that they should have different colors. The new screenshot looks nice. Is this using wynn colors but with coordinates changed to aqua (from white) and general text changed from gray to white?

Yes

**Pull request merged**
