### PR TITLE
feat: Display full quest info

### LINKED ISSUE #1730: [2.0.3] content book requirement parsing is missing/broken
For instance, the quest "Elemental Exercise" parses badly, likely due to the Quest Req. But we also need to parse the quest and profession requirements properly, and convert them to QuestInfo-style requirements.

### PR DESCRIPTION
**Pull request by kristofbolyai**
Depends on #1829, fixes #1730

Screenshots:
image
image
image

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Explaination for latest commit: 

Bugged:
image

Fixed:
image

**Comment by magicus** [comment]
I can't for the life of me see the difference between the bugged and the fixed tooltip screenshots..?

**Comment by magicus** [comment]
Also, did you check that it handles "Elemental Exercise"?

**Comment by kristofbolyai** [comment]
> Also, did you check that it handles "Elemental Exercise"?

It does, I can't screenshot it atm.

**Comment by kristofbolyai** [comment]
> I can't for the life of me see the difference between the bugged and the fixed tooltip screenshots..?

image

**Review by magicus — APPROVED** [review]

**Pull request merged**
