### PR TITLE
chore: New Crowdin updates

### PR DESCRIPTION
**Pull request by WynntilsBot**

### CODE REVIEW

**Comment by magicus** [comment]
@TUsama I'm not sure what is happening here. Is Crowdin trying to replace your translations with the old bad ones it had before? (I'm sorry but I can't tell the good ones from the bad ones...)

**Comment by TUsama** [comment]
well you need to pull the changes in GitHub to the crowdin, otherwise the crowdin will ignore these changes and overwrite it.

**Comment by TUsama** [comment]
you can check out [this](https://support.crowdin.com/github-integration/#:~:text=IP%20Addresses.-,Service%20Branches,-When%20translations%20are), It may help you do this sync trick.

**Comment by kristofbolyai** [comment]
> you can check out [this](https://support.crowdin.com/github-integration/#:~:text=IP%20Addresses.-,Service%20Branches,-When%20translations%20are), It may help you do this sync trick.

@DevScyu

**Comment by magicus** [comment]
We have changed setting at Crowdin, but it does not seem to recognize already pushed data. I will temporarily accept this regression, and then restore the proper Chinese translation.

**Review by magicus — APPROVED** [review]

**Pull request merged**
