### PR TITLE
chore: IntelliJ inspection profile fixes

### PR DESCRIPTION
**Pull request by magicus**
This will update the Artemis profile, add a new Artemis-mini profile (which basically should be clean at all times), and fixes the stuff that has regressed in Artemis-mini since I created it.

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Do we have to set it manually?

**Comment by kristofbolyai** [comment]
If so, maybe add docs?

**Comment by magicus** [comment]
Yes, you need to run "Analyze code" manually. 

I'm thinking of seeing if I can reshape this into a Qodana profile, to maybe run Qodana with "warnings" and "errors" or something like that, so that anything that triggers in the "mini" profile will get more or less a blocker. I don't know if or how that is possible though.

**Comment by magicus** [comment]
In the meantime, I'm planning to run it every now and then instead.

**Pull request merged**
