### PR TITLE
feat: Update the visuals of the custom player list

### PR DESCRIPTION
**Pull request by ShadowCat117**
Category titles now come from the vanilla list so when "Party" changes to "Island info" or "Raid info" it no longer still says party at the top.
Text shadow settings, default to normal.
Grey text no longer becomes black.
Wider texture to support longer names.

### CODE REVIEW

**Comment by magicus** [comment]
Looks nice! Just one question, the "scrolls" does not seem fully "attached" to the parchment background at the lowest point? Maybe you can make the background parchment a few pixels wider?

**Comment by kristofbolyai** [comment]
I'd assume it'd be nice to fix the FontRenderer custom color issue before merging this. Please give me a bit, and I'll take a look.

**Comment by kristofbolyai** [comment]
So is this ready now?

**Review by kristofbolyai — APPROVED** [review]

**Comment by ShadowCat117** [comment]
Should be!

**Pull request merged**
