### PR TITLE
fix: Container queries now work in various changing conditions

### PR DESCRIPTION
**Pull request by kristofbolyai**
This is the fix.. I have not been able to get this tested, but as far as I am aware, this should work. I will wait for a tester, than merge this.

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Aand this doesn't solve the issue for one tester. Perhaps @DonkeyBlaster could test it too, to see if it is completely bad...

**Comment by ryanzhoudev** [comment]
This seems to work for me, on two of the settings that didn't yesterday.

**Comment by kristofbolyai** [comment]
From discord:

Donkey's instance seem to be working without this...

Maybe this is a wynn thing, let's just keep this here for a while.

**Comment by kristofbolyai** [comment]
This is not needed, for now.

**Pull request closed without merging**
