### PR TITLE
fix: Various party management screen fixes [skip ci]

### PR DESCRIPTION
**Pull request by ILikePlayingGames**
- Fix texture not found in SuggestionPlayerWidget#renderWidget when trying to load the Steve skin for players with unknown skins
- Add pattern for new party leave message in Models.Party
- Fix "and" not being trimmed from the username of the last party member
- Hide party member column when the player is not in a party

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Looks good to me. Thank you for your contribution.

@DonkeyBlaster as the original creator, would you like to review this as well?

**Comment by ryanzhoudev** [comment]
> @DonkeyBlaster as the original creator, would you like to review this as well?

Yes please, thanks for notifying. My flight is arriving in around 11 hours so I'll look at it and merge then.

**Review by ryanzhoudev — COMMENTED** [review]
What you have here is fine, but a couple things I want to bring up:
- When you don't render the party list on the left when not in a party, the entire screen feels very off centered. Perhaps you could instead write a "Currently not in party" text in the center of the left half of the screen?
- When you create a party using the screen button and disband it with the button next to your name, under the "kick" column, the screen does not refresh and makes it seem like you are still in your solo party. Are you able to look into this as well? It's fine if you don't want to, just let me know.

Thanks for contributing!

**Comment by ILikePlayingGames** [comment]
Thanks for your feedback!

- I thought about that but the text was small and a lot of area was still blank, maybe I can make the text bigger and see.
- I guess Wynn fixed the missing period I reported, I’ll test later

**Comment by ILikePlayingGames** [comment]
Which one is better? (I committed top)
| Top | Middle |
| ----|--------|
| image | image |

Also Wynn didn't add a period, they removed one from the disband message.

**Comment by ryanzhoudev** [comment]
I kind of like the middle one more, it feels more in line with trying to take up screen space and is less off centered imo, but up to you. If you like what's here now, I am okay to merge.

**Comment by ILikePlayingGames** [comment]
I’ll switch it to the middle. I also want to add a party member count out of 10 somewhere.

**Comment by ILikePlayingGames** [comment]
New member count:

image

**Comment by ILikePlayingGames** [comment]
@DonkeyBlaster I’m done with the changes now
, it is ready to merge.

**Comment by ryanzhoudev** [comment]
Changes look good. Final thing I will ask of you is to align this title, so that it's in the middle like the Promote and Kick buttons. Then I will merge.
image

**Comment by ILikePlayingGames** [comment]
I've aligned it.

image

**Review by ryanzhoudev — APPROVED** [review]

**Pull request merged**
