### PR TITLE
chore: Use MixinExtras 0.2.0-beta.5

### PR DESCRIPTION
**Pull request by kristofbolyai**
This PR needed to bump all mod loaders. I selected latest for Fabric and Quilt, and the minimum version for Forge to work (due to how the other 20 releases does not affect us). With this, I needed to update the `quilt.mod.json` to the new specs.

### CODE REVIEW

**Comment by kristofbolyai** [comment]
@magicus Feel free to review this. Nothing will change, except some build.gradle changes to make production work (which I need to wait for LlamaLad7 to happen). This does some work from your 1.19.4 port, so at least it's diff will be a bit smaller :).

**Comment by kristofbolyai** [comment]
Please note that due to the nature of this PR, I would like to announce the loader version bumps. **Do NOT merge without announcing.**

**Comment by kristofbolyai** [comment]
And this is ready now. Tested on all mod loaders.

**Review by magicus — APPROVED** [review]
Looks good. Much cleaner now that the ugly workarounds are removed.

**Pull request merged**
