### PR TITLE
fix: Rotate minimap based on camera rotation instead of player rotation [skip ci]

### PR DESCRIPTION
**Pull request by jadedbay**
Added the option to rotate the minimap based on camera rotation.
This is useful for when using other mods that lets you rotate the camera without rotating the player eg. BetterThirdPerson.

### CODE REVIEW

**Comment by jadedbay** [comment]
I'm using an enum instead of a boolean now:
```java
private enum RotationType {
        STATIC,
        PLAYER,
        CAMERA
}
```
but I could just update `McUtils.player().getYRot()` to `McUtils.mc().gameRenderer.getMainCamera().getYRot()` instead and leave it as a boolean, because I don't really see any point in having the `PLAYER` (old rotation behavior) option since it has the same behavior as `CAMERA` in first and third person (only different in second person and when using mods that adjust how the camera works), and this would simplify the setting for users. Let me know if you want me to update it.

**Comment by kristofbolyai** [comment]
Is second person view also achieved by mods?

**Comment by jadedbay** [comment]
The third person view but you face yourself, sorry wasn't sure what to call it.

**Comment by kristofbolyai** [comment]
So all in all, this is just mod compatibility fix (that happens to fix a weird 3rd person view issue). Okay. Let's revert the boolean then, and keep the fix :)

**Comment by jadedbay** [comment]
Sure I'll make the changes now do you want me to just keep the variable named followPlayerRotation or change it to followCameraRotation?

**Comment by kristofbolyai** [comment]
Don't rename the config, otherwise it will be reset for users (unless you add upfixers for it). You can correct the en_us file though.

**Comment by magicus** [comment]
So what happens with this fix if I press F5 and view myself from the front? From the back?

**Comment by jadedbay** [comment]
There's no difference if you're facing the back of the player (since the camera and player are facing the same direction) but if you are looking at the player's face (F5 twice from first person) the minimap will be rotated so that its pointing the same way the camera is and not where the player is looking.

**Comment by magicus** [comment]
Hm, okay. Are you OK with this @kristofbolyai? If so, then so am I.

**Review by kristofbolyai — APPROVED** [review]
I think this is acceptable, the minimap should follow the camera rotation, not the player body (as it's an UI element).

**Comment by kristofbolyai** [comment]
Thank you for fixing this!

**Pull request merged**
