### PR TITLE
Fabric now loads resource files correctly

### LINKED ISSUE #39: Fabric does not load translation files in development environment

### PR DESCRIPTION
**Pull request by kristofbolyai**
Fixes #39.

### CODE REVIEW

**Review by P0keDev — APPROVED** [review]

**Comment by Incompleteusern** [comment]
gg

**Comment by magicus** [comment]
@kristofbolyai This looks like two different kinds of syntax to express the same thing? Can any one of them be turned into the other? (I think the latter looks more clear tbh).

**Comment by kristofbolyai** [comment]
> @kristofbolyai This looks like two different kinds of syntax to express the same thing? Can any one of them be turned into the other? (I think the latter looks more clear tbh).

What do you mean?

Fabric loader is the mod loader, and the resource loader is part of the Fabric API, but we don't need to depend on the API, just the module.

**Comment by magicus** [comment]
I mean:

```
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation(fabricApi.module("fabric-resource-loader-v0", rootProject.fabric_version));
```

Looks like it could be:
```
    modImplementation(fabricApi.module("fabric-loader", rootProject.fabric_version));
    modImplementation(fabricApi.module("fabric-resource-loader-v0", rootProject.fabric_version));
```
(or possible `fabric-loader-v0`..?)

**Comment by kristofbolyai** [comment]
> I mean:
> 
> 
> 
> ```
> 
>     modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
> 
>     modImplementation(fabricApi.module("fabric-resource-loader-v0", rootProject.fabric_version));
> 
> ```
> 
> 
> 
> Looks like it could be:
> 
> ```
> 
>     modImplementation(fabricApi.module("fabric-loader", rootProject.fabric_version));
> 
>     modImplementation(fabricApi.module("fabric-resource-loader-v0", rootProject.fabric_version));
> 
> ```
> 
> (or possible `fabric-loader-v0`..?)

Not sure actually, see https://github.com/FabricMC/fabric for modules

**Comment by magicus** [comment]
Ah, I see, the former is the Fabric loader, and the latter is (part of) the Fabric API, which are different beasts. I get it. Still a bit annoying with the difference in syntax. I'll check if it's possible to use the `modImplementation()` version for the loader as well, even if it's not using `fabricApi.module`.

**Pull request merged**
