### PR TITLE
fix: Use Wynntils' WynnData fork in the mod

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
https://github.com/Wynntils/WynntilsWebsite-API/pull/108

**Comment by magicus** [comment]
You don't need to bump the version number to update an URL, just if you want to add a new url instance.

**Comment by kristofbolyai** [comment]
Okay, got it. But it might be nicer overall..

**Comment by magicus** [comment]
I dunno, really. If we increase it every time we change an URL, it will start approaching very high numbers. I think it is better to try and keep the version number changes to actually mean breaking changes to the format.

**Pull request merged**
