### PR TITLE
fix: IF batching on hud text

### PR DESCRIPTION
**Pull request by HalcyonSuoh**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Can you remove IF from the incompatibility lists from quilt/fabric?

**Comment by HalcyonSuoh** [comment]
> Can you remove IF from the incompatibility lists from quilt/fabric?

failed to find IF entry in quilt.mod.json, other than that, sure

**Comment by kristofbolyai** [comment]
> 
> 
> 
> 
> 
> 
> > Can you remove IF from the incompatibility lists from quilt/fabric?
> 
> 
> 
> failed to find IF entry in quilt.mod.json, other than that, sure

Might not be in there.

**Review by kristofbolyai — APPROVED** [review]

**Comment by magicus** [comment]
I had not heard about IF before, but they seem to claim good interoperability, so I opened a bug on them to give them chance to fix the problem on their side.

https://github.com/RaphiMC/ImmediatelyFast/issues/126

However, I don't know what the actual problem was 😜 so if anyone wants to add such an explanation to the bug, I think it would be nice.

**Pull request merged**
