### PR TITLE
fix: Add a missing translation

### PR DESCRIPTION
**Pull request by DevChromium**
There was a missing translation for the horse mount feature, this pr fixes it.

### CODE REVIEW

**Review by kristofbolyai — DISMISSED** [review]
Github had a stroke seems like.

**Comment by magicus** [comment]
The diff looks weird. The whole file seems replaced. Is that what you mean by stroke, @kristofbolyai? 
@DevChromium  Are you sure you don't have any line ending issues? This looks like you're trying to introduce a CR/LF line ending or such.

**Comment by kristofbolyai** [comment]
> The diff looks weird. The whole file seems replaced. Is that what you mean by stroke, @kristofbolyai? 
> 
> @DevChromium  Are you sure you don't have any line ending issues? This looks like you're trying to introduce a CR/LF line ending or such.

Yeah, it is weird, not sure why the diff is wrong.

**Comment by DevChromium** [comment]
> 

Might be my IntelliJ settings, is there any way to check this?

**Comment by kristofbolyai** [comment]
> Might be my IntelliJ settings, is there any way to check this?

Spotless is not happy, perhaps run it. `./gradlew spotlessApply`.

**Comment by magicus** [comment]
@DevChromium Possibly. We should perhaps add an .gitattribute file as well, to force git to do the right thing.

As for checking in IntelliJ, I don't have it available right now, but the status bar at the bottom should say LF or CR/LF. It should be the former.

**Comment by magicus** [comment]
Yeah, that confirms my suspicions:

```
 The following files had format violations:
      src/main/resources/assets/wynntils/lang/en_us.json
          @@ -1,57 +1,57 @@
          -{\r\n
```

**Comment by DevChromium** [comment]
image

Whenever I commit, it already runs spotless from the git hook, could  this be the issue>

**Comment by magicus** [comment]
Yeah, mabe the hook does the wrong thing on windows. Sorry, I only tested it on mac.

**Comment by kristofbolyai** [comment]
> Yeah, mabe the hook does the wrong thing on windows. Sorry, I only tested it on mac.

Seems to work on windows when I tried it.

**Comment by DevChromium** [comment]
> > Yeah, mabe the hook does the wrong thing on windows. Sorry, I only tested it on mac.
> 
> Seems to work on windows when I tried it.

Must be my IntelliJ settings then

**Comment by magicus** [comment]
It can be a weird combination of gradle and spotless stuff or whatnot that uses the wrong line endings.

**Comment by DevChromium** [comment]
When I build locally, spotless doesn't error. So it probably is Git that is using the wrong line endings.

**Comment by kristofbolyai** [comment]
Let's see if it works after merging #91

**Comment by kristofbolyai** [comment]
Fixed it 🥰

**Review by kristofbolyai — APPROVED** [review]

**Pull request merged**
