### PR TITLE
feat: Add rainbow donator tag, fix developer tags [skip ci]

### PR DESCRIPTION
**Pull request by kristofbolyai**
[Kooha-2024-05-14-17-17-42.webm](https://github.com/Wynntils/Artemis/assets/49001742/05f740f3-5104-4dcc-adcd-28330e3d938b)

(The video is laggy, the animation is not)

### CODE REVIEW

**Comment by ShadowCat117** [comment]
Nice, now I won't get people asking me what a Wynntils Moderator is all the time 😅

**Comment by magicus** [comment]
My English skills might not be correct, but I think "donor" is the preferred noun, instead of "donator". Someone who speak English natively can perhaps comment?

**Comment by kristofbolyai** [comment]
It's been donator since legacy, only the rainbow coloring changed here.

**Comment by magicus** [comment]
I know. Sorry, I should have said that. I have never seen a "donator" tag in the wild so I had never thought about it, but now that I saw your screenshot I reacted to it. You are correct that this is a separate bug.

**Pull request merged**
