### PR TITLE
fix(HighlightMatchingItemsFeature): Search now persist through page switching on the same screen

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Review by Incompleteusern — COMMENTED** [review]
Why was the textbox clearing if only the container contents was changing?

**Comment by kristofbolyai** [comment]
> Why was the textbox clearing if only the container contents was changing?

I think because the screen re-inited.

**Comment by Incompleteusern** [comment]
If I understand correctly, one container instance can switch between multiple screens?

**Comment by kristofbolyai** [comment]
> If I understand correctly, one container instance can switch between multiple screens?

Yeah. I think page switching opens a new screen (and closes the old one)

**Review by Incompleteusern — APPROVED** [review]

**Pull request merged**
