### PR TITLE
Silence a few warnings from Qodana

### PR DESCRIPTION
**Pull request by magicus**
It was a bit tricky to determine the names of the inspections. I ended up downloading the report, looking through the files until I found the `inspectionName` key, and then grepped that. Don't know if there is a better way.

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]

**Comment by magicus** [comment]
Argh, `maven.parchmentmc.org` is down, so the build does not succeed, and hence I cannot merge this. :-( Stupid systems. I think we need to allow main developers (me, you and P0ke) to override this restriction, not only @DevScyu.

**Comment by kristofbolyai** [comment]
I think we can leave the double spaces and use the escaped version (%s). As for finding these tags, you can download Qodana report, use python http server host and open it, and you get a nice GUI where you can disable inspections and download the new qodana.yml.

**Comment by magicus** [comment]
I've never even heard about having `%s` as an escape for space in regexp. It does not work on regex101.com, which is my standard go-to place for testing out regexps. I can't see any gain in changing real, working rexeps to some non-standard variant, just to make a stupid warning in Qodana keep quiet.

**Comment by kristofbolyai** [comment]
Oh sorry, it is \s. https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp

**Comment by magicus** [comment]
Well, that is not the same. ` ` is just a single space character. `\s` matches all kinds of whitespace. I still claim this Qodona rule is dumb as f*ck.

**Pull request merged**
