### PR TITLE
refactor: Fix remaining raw use of generic classes

### PR DESCRIPTION
**Pull request by magicus**

### CODE REVIEW

**Review by kristofbolyai — COMMENTED** [review]
Code looks fine. Let me test it.

**Review by kristofbolyai — APPROVED** [review]
Can't see anything broken from launching and checking some settings. Can you test too?

**Comment by magicus** [comment]
I did some in-depth testing of enum json reading, and a generic check that it was not DOA. I think that is enough.

**Comment by kristofbolyai** [comment]
Sounds good.

**Pull request merged**
