### PR TITLE
chore: Move all regex testing from regexr.com to unit tests

### PR DESCRIPTION
**Pull request by magicus**
If something needs doing, do it yourself.

I have now ported all regex tests from regexr.com to our unit tests. (At least, those that had a regexr.com link in the source).

A handful of tests did not actually work, or did not work if I updated the regexr test with the current value of the pattern. I have just commented these out -- we should really investigate if the wynn format has changed, of if we have actually broken the regex pattern.

I made a few changes to the regexr tests if they failed, if they contained superfluous `§r` codes. I believe these changes are safe to do.

### CODE REVIEW

**Comment by magicus** [comment]
I chose to include the name of the test at the pattern for a few different reasons, even if it was systematically generated:

1) It reminds folks to update the test
2) It makes it easy to go to the test function by a copy and global search
3) It makes it clear which patterns have tests and which have not

**Review by kristofbolyai — APPROVED** [review]
DId you fix up the local/global chat patterns in the process? I don't think we've ever updated them to the new Unicode Wynn format.

**Comment by magicus** [comment]
No, I did not change them. Someone already had.

**Comment by magicus** [comment]
The commented-out tests should be reenabled, but we need to determine if the regexps have changed wrongly, or if the old test strings are no longer valid. I'll leave at least that part to someone else...

**Comment by kristofbolyai** [comment]
> The commented-out tests should be reenabled, but we need to determine if the regexps have changed wrongly, or if the old test strings are no longer valid. I'll leave at least that part to someone else...

Ill make a follow up, don't worry about it.

**Comment by magicus** [comment]
And then of course we should add tests for more regexes. :) Perhaps not all, some are really trivial, but there are many non-trivial ones that really should have testing, like all in MessageType, both background and foreground.

And hopefully this makes it easier to always add tests in the future when modifying or adding a regex.

**Pull request merged**
