### PR TITLE
Configs

### PR DESCRIPTION
**Pull request by Incompleteusern**
This should eventually be a usable config system

This is nowhere near complete.
Here's a roadmap of what is to be done.
- [ ] Setting annotation parsing through reflection
- [ ] Rudimentary config gui
- [ ] Saving settings to json for now

### CODE REVIEW

**Comment by magicus** [comment]
Some general thoughts about config (not necessarily related to the code in this PR :-))

* Do we really want to keep the old UI, or should we chose one of the standard frameworks for making config UIs (like Cloth)?
* We need to make sure that configuration options has a bi-state: "is it default or locally configured?" and "the actual value". And only values which override the default should be stored. This way, we can easily change the default value. Compare with eg. about:config in Firefox.

**Comment by kristofbolyai** [comment]
> * We need to make sure that configuration options has a bi-state: "is it default or locally configured?" and "the actual value". And only values which override the default should be stored. This way, we can easily change the default value. Compare with eg. about:config in Firefox.

Doesn't this hint that we want to have configs locally editable in some form? If so, we would need to make sure we handle configs correctly.

- I would imagine config options to be bi-state, but in a different way: "default" or "non-default". 
- Make every setting have a save timestamp and have it stored in both local and cloud config (although this is not that straight forward locally, if we want to locally edit settings, we don't want to edit a "save timestamp" as well. Solution could be the file's actual metadata save time, thought I am not sure if we should use that.). 
- Every time we load the game, we would just set everything to "default" state, then load configs from file and cloud and change related configs to a "non-default" state.. Then, if there are conflicts use timestamps to merge them, save them and upload to cloud.

**Comment by Incompleteusern** [comment]
> * I would imagine config options to be bi-state, but in a different way: "default" or "non-default".

I imagine "default" configs to simply not be saved either locally or in the cloud.

> * Every time we load the game, we would just set everything to "default" state, then load configs from file and cloud and change related configs to a "non-default" state.. Then, if there are conflicts use timestamps to merge them, save them and upload to cloud.

It could also be possible to the user handle these "merge conflicts" by themselves.

**Comment by kristofbolyai** [comment]
> I imagine "default" configs to simply not be saved either locally or in the cloud.

Yeah, me too, though maybe we should save all configs locally and only non-defaults in the cloud. It would greatly help with configurability using files, otherwise we would need to document setting config literals somewhere.

**Comment by kristofbolyai** [comment]
> It could also be possible to the user handle these "merge conflicts" by themselves.

Thought about this too, but I am not sure if it would be used and this can make configs much more complicated than needed.

**Comment by magicus** [comment]
My suggestion (drawing inspiration from vscode) is that we have a user-prefs.json kind of file, that is empty unless the user has made any changes away from default. We can also have a default-prefs.json file, distributed from Athena, that contain the default values. This way we can easily change default values. When looking up what value to use (at init or when prefs reload is triggered, by whatever means), we first look in user-prefs.json, and if it is not found there, we fall back to default-prefs.json.

@kristofbolyai I'm not sure I understand your distinction between "cloud" and "local". Are you saying that, in addition to the kind of logic I described above, we should have like "cloud-user-prefs.json" and "local-user-prefs.json", where the latter is not uploaded and/or shared between computers/MC instances? 

I think the use case for this is slim, and it risks complicating things a lot. (The only use case I can imagine is like, you have two computers, one beefy and one old, and you want to have some performance heavy setting different on the two computers. Is that even a scenario we need to support?)  If we do, I suggest that the "local-user-prefs.json" should be rather like a "local-override.json", and that editing it will *only* be supported by manually editing the json file. Not through the UI, where any changes you make go into the "[cloud-]user-prefs.json" And when looking up config values, we check local-override.json first, then users-prefs.json and then default-prefs.json. That way, we can allow the user to have local override, but it's a bit tricker to get, without messing the UI for everyone else.

**Comment by magicus** [comment]
And I'd like to stress that if we have e.g. default value "false" for some setting, the user sets it to "true" in the UI, then true is stored in user-prefs.json. However, toggling the value back to "false" means that "false" will be written to user-prefs.json. This is important, to allow users to fix a value even if we were to change the default. Instead, if they want to remove their customization, they'll need to press a "reset" button. (Which is grayed-out unless a custom value is set.)

**Comment by kristofbolyai** [comment]
@magicus I am only suggesting that we should have non-cloud saved configs (though @Incompleteusern wanted something like that?), I am just simply saying that we should have configs locally editable and copyable as a file as it is not the case with Wynntils (to my knowledge).

**Comment by magicus** [comment]
Merging changes is tricky. There is really never a good way of doing it, and to make it "properly" requires difficult UI interfaces.

I think the "global timestamp" is enough. That is, you store the time stamp for when user-prefs.json were last edited locally, and when it was last updated in the cloud. If the cloud is newer than local, just overwrite the local file. If local is newer than cloud, then upload to the cloud.

In theory, if you change settings in parallel on two different instances, without immediate internet access for cloud updating, we can get into a conflicting mode, where we e.g. override setting A on computer A´, and override setting B on computer B´, and then one of these changes will be lost. 

But given that we sync continuosly, and that you can only be logged in to Wynncraft from one computer at a time, this is so unlikely to happen, and the consequences to small if it were to happen, that we can fully ignore it.

**Comment by magicus** [comment]
@kristofbolyai If you and @Incompleteusern are happy with the local file override being just a power-user tool, then I suggest we follow the outline I sketched above, with three files, here repeated with suggested paths:
 * .minecraft/config/wynntils/user-prefs.json  <-- local override
 * .minecraft/wynntils/account/user-prefs.json  <-- synced to cloud
 * .minecraft/wynntils/web-data/default-prefs.json <-- statically downloaded from Athena
 *

**Comment by kristofbolyai** [comment]
> .minecraft/config/wynntils/user-prefs.json <-- local override
> .minecraft/wynntils/account/user-prefs.json <-- synced to cloud
> 

I think these can be easily mixed up, perhaps just name the later one to `cloud-user-prefs.json` (our cloud-prefs)

**Comment by magicus** [comment]
I think "cloud" is vague and not really conveying the important part, that this is the main user preference file. (That it is cloud synced is kind of secondary to it's primary purpose.)

Maybe rename the first file to .minecraft/config/wynntils/user-prefs-override.json ?

**Comment by magicus** [comment]
We also normally don't store stuff in the config directory, which is traditionally coupled to the specific minecraft instance. So the placement as well as the name should indicate what the file is about. I could even argue that we should not even create the file, just read it if it exists.

**Comment by magicus** [comment]
(But otoh it might be helpful to create an empty file if it does not exist. I could go either way on this.)

**Comment by kristofbolyai** [comment]
Also, uh, maybe make uuid specific folders for configs? Or how are you planning to manage that?

**Comment by magicus** [comment]
How do you mean? What configs need what UUIDs?

**Comment by kristofbolyai** [comment]
> How do you mean? What configs need what UUIDs?

Configs would be put in a folder representing the user's uuid so it supports multiple accounts per instance and also is easy to find a profile's config.

**Comment by magicus** [comment]
That'd be kind of a new functionality..? The .minecraft/config folder, at least, assumes that it contains instance-wide configuration. 

Do we currently have per-user uuid configs in .minecraft/wynntils?

What is the use case here? Multiple people sharing the same minecraft instance; is that something commonly done? 🤔

**Comment by kristofbolyai** [comment]
> That'd be kind of a new functionality..? The .minecraft/config folder, at least, assumes that it contains instance-wide configuration. 
> 
> 
> 
> Do we currently have per-user uuid configs in .minecraft/wynntils?
> 
> 
> 
> What is the use case here? Multiple people sharing the same minecraft instance; is that something commonly done? 🤔 

I can see this getting used. Also, let's assume we don't separate by uuid, and the player uses 2 accounts with the same instance (alt accounts, possibly at the same time), what happens if configs get changed? I can see that result in chaos and that was my main thought as to why we should have them separated into specific folders.

**Comment by magicus** [comment]
So, basically, replace `minecraft/wynntils/account/user-prefs.json` with `minecraft/wynntils/accounts/<uuid>/user-prefs.json`? Fine, works for me. I still think the local override should be non-uuid-specific, since that is how the config directory normally works (and I don't think it will be often used, so let's not overcomplicate it.)

Cached data from athena (maps, NPCs etc) can and should be shared between all accounts. So basically we'll have two main directories in wynntils -- "web-data" (or perhaps even better as "cache") which contains stuff which can be shared between accounts, and a "accounts/<uuid>" which contain settings, user-added POIs, and that are synced with the users account.

**Comment by kristofbolyai** [comment]
> So, basically, replace `minecraft/wynntils/account/user-prefs.json` with `minecraft/wynntils/accounts/<uuid>/user-prefs.json`? Fine, works for me. I still think the local override should be non-uuid-specific, since that is how the config directory normally works (and I don't think it will be often used, so let's not overcomplicate it.)
> 
> 
> 
> Cached data from athena (maps, NPCs etc) can and should be shared between all accounts. So basically we'll have two main directories in wynntils -- "web-data" (or perhaps even better as "cache") which contains stuff which can be shared between accounts, and a "accounts/<uuid>" which contain settings, user-added POIs, and that are synced with the users account.

I agree, but one small thing. Wynntils currently caches user data, so when using multiple accounts on the same instance we cache wrong user info. We should definitely fix that (thought it is not completely related to configs).

**Comment by Incompleteusern** [comment]
I've been thinking and my current thought is that local file modification should not be supported. For importing files a custom import file button should be used imo

**Comment by magicus** [comment]
Skipping that will simplify things, and it will not be a regression wrt to legacy Wynntils. I think we can at least proceed without local settings for now. It can always be added later, if we design things correctly.

**Pull request closed without merging**
