### PR TITLE
Make Loom generate only client runs in IntelliJ

### PR DESCRIPTION
**Pull request by magicus**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
What docs did you use for this? Because there is some other thing they call client only jars iirc.

**Comment by magicus** [comment]
I asked for advice in the Architectury discord, and got this reply: https://discord.com/channels/792699517631594506/1013533572914753536/1013536825228415056
> add loom.clientOnlyMinecraftJar() to the root build.gradle in subprojects

**Comment by magicus** [comment]
It is implied, but not documented, at https://fabricmc.net/wiki/documentation:fabric_loom, which has the example:
```
	// When set only server related features and jars will be setup.
	serverOnlyMinecraftJar()
```

**Review by kristofbolyai — APPROVED** [review]
Should be okay then. This should improve AW/AT processing time too.

**Comment by magicus** [comment]
AW/AT?

**Comment by kristofbolyai** [comment]
Access widener/Access transformer. 
When remapping jars, now they can skip the server ones.

**Comment by magicus** [comment]
Ah. Yeah.

**Pull request merged**
