### PR TITLE
Fix negative ID chances

### PR DESCRIPTION
**Pull request by ryanzhoudev**
Before:
image
After:
image

Fixes negative ID increase and decrease chances being reversed

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Actually instead of inverting that  there, try to invert it in the actual class it's calculated in

**Comment by Incompleteusern** [comment]
I feel as though this doesn’t properly address the root issue, also does it work for negative inverted ids

**Comment by kristofbolyai** [comment]
> I feel as though this doesn’t properly address the root issue, also does it work for negative inverted ids

Actually it does not work, it should be an xor there, not or.

**Comment by Incompleteusern** [comment]
Also imo instead of this requiring changing the comment on getChances, to have it automatically handle negative ids correctly, which I can try to do later.

this meand that isInverted should autoxor with whether it’s negative in the function itself

**Comment by kristofbolyai** [comment]
Let's close this and open a new PR fixing the root cause whenever someone get's into fixing so. Opened #68 for the issue.

**Pull request closed without merging**
