### PR TITLE
fix: Properly detect class joining

### LINKED ISSUE #2593: Entering the class edit screen causes /guild xp to be run multiple times upon join
**Version:** 1.2.22

### Expected behaviour

Editing a class would have no impact and the /guild xp command would only be run once upon joining.

### Actual behaviour

The /guild xp command will be run for each time you open the class edit menu once you join.

### Steps

1. Open the class selection screen
2. Press the edit button
3. Exit the class edit menu
4. Repeat steps 2-3 *n* times
5. Join with a class
6. /guild xp will be run *n* times

### Visual steps

https://github.com/Wynntils/Artemis/assets/71361356/e33dd560-dc34-4fc7-b65b-b92b674487ff

### PR DESCRIPTION
**Pull request by kristofbolyai**
Previously, we detected "any" clicks that was not air, so the edit buttons could "signal" a class update..

Fixes #2593

### CODE REVIEW

**Comment by ShadowCat117** [comment]
I was going to suggest maybe we should start parsing gamemodes from this but it seems like we need to 
image

**Review by magicus — APPROVED** [review]
I think this looks good but did not scrutinize it.

**Comment by kristofbolyai** [comment]
Okay @ShadowCat117, I made the regex support game modes, but I did not add any functionality to parse/display it.

**Comment by ShadowCat117** [comment]
That's fine, I have this screen on my todo list for a redesign anyway so unless someone gets to it first I'll display them then :)

**Review by ShadowCat117 — APPROVED** [review]

**Pull request merged**
