### PR TITLE
Fix @Shadow warning in build

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by magicus** [comment]
I think it was this way originally, but someone removed the generification..? But this solves the warning?

**Comment by kristofbolyai** [comment]
> I think it was this way originally, but someone removed the generification..? But this solves the warning?

It does solve the warning, not sure when it was changed.

**Comment by magicus** [comment]
Checking history... it was done in c038dd7c7d43d4a5080ed8caf88493ad7c6499b8, which says it fixes #12.

**Comment by magicus** [comment]
@Incompleteusern The PR for #12 does not say why this was changed. Do you remember why you removed the generification?

**Comment by Incompleteusern** [comment]
I think it didn't match the signature for the method when I compiled it

**Comment by magicus** [comment]
Ok so if this change works then you have no problem with it?

**Comment by Incompleteusern** [comment]
Definitely yes

**Review by magicus — APPROVED** [review]

**Review by Incompleteusern — APPROVED** [review]

**Comment by Mari023** [comment]
I think this doesn't work outside of dev.
see [this crash](https://hst.sh/javotiluro) (link copied from discord)
build since +12 (when this PR got merged) don't work

**Pull request merged**
