### PR TITLE
fix: fix wrong preposition in settings export tooltip [skip ci]

### PR DESCRIPTION
**Pull request by Twisted-Code**
following up on #2987, I fixed the lang. yay for simple first contributions?
Based against main because I saw other PRs doing it (CI right?) & commit summary should be satisfactory, however, I can change either of these easily enough if needed.

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]

**Comment by kristofbolyai** [comment]
Thanks

**Comment by Twisted-Code** [comment]
I've been meaning to ask: why do you skip CI on so many PRs? I see it (or rather, the slightly mangled equivalent; see #2771) all the time in the generated change logs. Was wondering whether I should have included it in my PR title —would that have skipped the (in this case probably unneeded) `Spotless and Build` check— and now I'm wondering why you added it afterwards? The main reason I could think of would be if your trying to save on your Actions quota?

**Comment by kristofbolyai** [comment]
https://github.com/Wynntils/Wynntils/issues/2769

**Comment by magicus** [comment]
@kristofbolyai We don't have a good story for how to update ChatGPT generated translations, right? I'm guessing this error has propagated to all translations. It's not terribly important per se, but I'm wondering if there is a way we could keep translations up-to-date, instead of just the one-shot translation we did.

**Pull request merged**
