### PR TITLE
(WIP) feat(raidInfo): Raid tracker feature

### PR DESCRIPTION
**Pull request by DevChromium**
**This pull request  is a Work in Progress**

This feature will allow the player to record their raids and reflect on how well/bad they did during it. The player will be able to see which rooms they visited, how much damage they did and how much they took themselves. It will also show which powerups they chose.

### Todo List

- [ ] `/raid start` - to start recording a raid
- [ ] `/raid stop` - to stop recording a raid when needed
- [ ] `/raid save <name>` - to save the raid in a file
- [ ] `/raid delete <name>` - to delete a saved raid
- [ ] `/raid folder` - to open the raid folder

### CODE REVIEW

**Comment by magicus** [comment]
Just curious, is this a port of an existing feature, or completely new functionality? (If this exists in legacy, I've missed it. Then again, I've not reached raiding maturity yet... :-))

**Comment by DevChromium** [comment]
> Just curious, is this a port of an existing feature, or completely new functionality? (If this exists in legacy, I've missed it. Then again, I've not reached raiding maturity yet... :-))

It is a completely new feature, it'll be like /lootrun but for raids :)

**Comment by magicus** [comment]
Nice! It'll be good to have some carrots, and not only sticks, for moving folks off Legacy. :) Just be aware that it might be a while before anyone is seriously able or willing to use Artemis for actual game play.

**Comment by kristofbolyai** [comment]
@DevChromium Do you still want to do this? Should we keep this open or will you reopen it when you have time?

**Comment by DevChromium** [comment]
> @DevChromium Do you still want to do this? Should we keep this open or will you reopen it when you have time?

It can be closed, thos project was a bit too hard for me. It's still a nice feature to be implented at some point later down the line.

**Pull request closed without merging**
