### PR TITLE
WynntilsItemGuideScreen: Do not keep items in memory after opening screen once

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
@magicus did you happen to miss this in the backlog of notifications :) ?

**Comment by kristofbolyai** [comment]
Anyways, I need this to be merged for my next PR, so if anyone has concerns, let me know.

**Comment by magicus** [comment]
Yes, I just looked the other way a few days, and then I have a trillion notifications. :) You guys are too darned productive! ;-)

But seriously, we are getting very close to feature parity with Legacy. I think we need to discuss what more is needed before we can call it an alpha. (For a "beta" label, I think we need fix some more outstanding issues.)

**Comment by Incompleteusern** [comment]
> Yes, I just looked the other way a few days, and then I have a trillion notifications. :) You guys are too darned productive! ;-)

It's mostly bolyai :).

**Pull request merged**
