### PR TITLE
feat: update CHS locale

### PR DESCRIPTION
**Pull request by TUsama**
I have to made a new simplified chinese locale cuz the current machine translation is too ridiculous.

currently only about 50% contents have been translate. I'll finish this in next PR(or this, regarding the merge time, I highly recommand the repo maintainer merge this  PR rn tho).

also, thanks for your guys work, it's excellent!

### CODE REVIEW

**Comment by magicus** [comment]
We had some idea to use Crowdin for translations, but to be honest, that has not really worked. And since we already have the chinese translation included, we might as well accept corrections to it.

**Comment by magicus** [comment]
@TUsama Please have a look at the translation present in https://github.com/Wynntils/Artemis/pull/1191.

It seems to conflict with your changes, but unfortunately I cannot judge or compare the quality of neither of them,

**Comment by TUsama** [comment]
you can merge the https://github.com/Wynntils/Artemis/pull/1191 first and I'll deal with the conflict. the changes made in that PR are just some line deletions. 
But to be honest I do roll back many translated lines to English, I'll finish that ASAP.

**Comment by kristofbolyai** [comment]
Don't forget to use conventional commits as PR name.

**Comment by magicus** [comment]
We'll need some infrastructure changes to integrate #1191, but I have started working on getting these in place.

**Comment by RisingInIris2017** [comment]
Quite interesting.
Have a quick look at this. Though TU's translations are not fully completed, we can definitely see that it is done by a well-trained *human* translator, rather than someone who may be unfamiliar with both Wynncraft and English language.
Hope this pull request will be merged after TU completes the whole translation.

**Comment by magicus** [comment]
@RisingInIris2017 Thanks for your input on the quality of this translation.

**Comment by magicus** [comment]
@TUsama Now #1191 has been integrated. I apologize if it is a rough job to merge this with your PR.

**Comment by TUsama** [comment]
sorry for the push spam, just wanna change the commit name.

it's about 84% content of this file has been translated, the rest of that may be finished someday, but not in this PR.

this PR is ready to be merged.

**Comment by magicus** [comment]
Keys that are not translated should be removed; the English version will be used as fallback automatically.

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
@TUsama Thanks for your contribution! 

We are trying to get a process working where we can use Crowdin for translations. In theory, you could go to https://crowdin.com/translate/wynntils-mod/41/en-zhcn to make future changes. However, we'd need to streamline our process about this. I'm guessing right now translations get stuck there awaiting approval. If you want to continue translating into Chinese, we should discuss in discord how to proceed.

**Comment by TUsama** [comment]
I know there is a crowdin you guys use to receive the locale, but tbh I don't find the open link about that in the DC or GitHub page. That's the major reason I am here to use the PR.
and the other reason is, I have my own translation memories stored in my PC, and I'll lose their help if I use the online CAT.

**Comment by magicus** [comment]
That's because we have not really started using Crowdin properly. I assume it will be more helpful in the future for incremental changes. For major additions like this, I think PRs work fine.

**Comment by ghost** [comment]
看了眼翻译文件，只能说翻译的质量比我高。我根本联系不上国内的玩家群体所以我都不好确定某些单词应该怎么翻译，然后翻译就慢下来了。期待完全翻译好的版本。

**Comment by magicus** [comment]
@anonymhe Please keep to English in the public discussion on Github.

**Comment by ghost** [comment]
> @anonymhe Please keep to English in the public discussion on Github.

oops, my bad.
I just wanna say that this translation is more "complete" compare to mine and he pulls it, so great job.

I just kinda stuck at some translation because I can't reaching out to the Chinese Wynncraft community. I can't just simply translate something without context and that will make my translation looks terrible. (I really don't wanna make any mistakes in there. That's my ego)

Also I'm not that skilled at Wynncraft, I just doesn't has much experience. So I'm glad that someone better than me can finish this translate thing.

You can use Google translate on that reply, sorry for the inconvenience.

**Comment by magicus** [comment]
@TUsama Did you notice that your input is required in https://github.com/Wynntils/Artemis/issues/1970?

**Comment by TUsama** [comment]
done, I sent the message about two days ago and it now disappears, weird.

**Comment by magicus** [comment]
Thanks! We had to re-create the bug since we originally targeted GPL as the new license, but it turned out to be unsuitable. I guess you replied to the first, now closed, bug.

**Pull request merged**
