### PR TITLE
Guides: Add Emerald Pouch and Powder guides

### PR DESCRIPTION
**Pull request by kristofbolyai**
image
image

### CODE REVIEW

**Comment by Incompleteusern** [comment]
At some point we should combine what will be four item guides with a common superclass and itemstackbutton class.

**Comment by kristofbolyai** [comment]
> At some point we should combine what will be four item guides with a common superclass and itemstackbutton class.

We could yeah. I just didn't want to add a fourth superclass...
image
image
image

**Comment by Incompleteusern** [comment]
> > At some point we should combine what will be four item guides with a common superclass and itemstackbutton class.
> 
> We could yeah. I just didn't want to add a fourth superclass... image image image

Haha, reasonable enough

**Comment by magicus** [comment]
Is this for feature parity with legacy? I've never felt the need for a emerald pouch guide. There's just so few that you understand quickly where the LE merging cutoff is, and that's all that matters.

And powder guide. It's kind of like a "class guide". It's a core game concept.

(But maybe we should have an "Archetype guide"..? I am utterly lost at these new archetypes, what abilities they can have, what you chose to forego if you select one over the other)

**Comment by kristofbolyai** [comment]
> Is this for feature parity with legacy? I've never felt the need for a emerald pouch guide. There's just so few that you understand quickly where the LE merging cutoff is, and that's all that matters.
> 
> 
> 
> And powder guide. It's kind of like a "class guide". It's a core game concept.
> 
> 
> 
> (But maybe we should have an "Archetype guide"..? I am utterly lost at these new archetypes, what abilities they can have, what you chose to forego if you select one over the other)

Legacy has this too. Atm this is "needed" so people can favorite pouches and powders

**Comment by magicus** [comment]
Ah, the favorite thing. I see.

**Review by magicus — APPROVED** [review]

**Pull request merged**
