### PR TITLE
feat: Implement most `fuy.gg/avomod` and `Wynntils Legacy` features that fit into Artemis

### PR DESCRIPTION
**Pull request by kristofbolyai**
# Important
When you start work on a feature, create a separate branch, based on this PR's branch. Then target this branch with a PR, whenever the feature is ready. **Please tick the feature you are working on before it's PRd, so others don't start the work on it.**

## Features/Overlays
- [x] Item Filter UI
- [x] AttackTimerOverlayFeature (Improved handling for territories cut off scoreboard, either vertically, or horizontally + overlay fitting changes) 
- [x] WeeklyBackupFeature
- [x] AuraNotificationFeature (Plays a sound on aura)
- [x] BeaconOnTimersFeature (Beacon at war locations)
- [x] BombBellFeature (Overlay)
- [x] FilterGuildBankMessagesFeature (Possible with chat tabs)
- [x] Filter guild rewards
- [x] LootrunDryStreakFeature (For new lootrunning)
- [x] PrintTimesFeature (Time taken to complete raid)
- [x] RaidOverlayFeature (Title and room progress)
- [x] RevealNicknamesFeature
- [x] SeasonLeaderboardFeature (Adds guild tag and SR above lower guild to leaderboard in guild hall)
- [x] ServerInfoFeature (Overlay showing current world & newest world with uptime, only shows when player list open)
- [x] TerritoryHelperMenuFeature (Planned)
- [x] TowerStatsFeature (Displays tower stats after war)
- [x] WarHornFeature (Sound when war starts)
- [x] WarInfoOverlayFeature (Time in war, tower ehp, dps stats and time left)
- [x] ProfessionHighlightFeature (legacy)

## Commands
- [x] onlinemembers <guild> guild online members
- [x] lastseen <player> online or last seen time
- [x] add /switch clickable to /server command, add aliases
- [x] playerguild <player> guild name, rank and days in guild
- [x] wars <duration> wars since a duration
- [x] lootrun drystreak pulls without mythic
- [x] lootrun drystreak average average pulls per mythic

### CODE REVIEW

**Comment by Essentuan** [comment]
AttackTimerOverlayFeature relies mostly on the chat for timers and not the scoreboard. This does mean it can be wrong on certain swamp territories (class -> log in -> timer on scoreboard -> guesses the wrong territory) but overall its better. (It can also display more timers; probably too many)

AutoSkipDialogueFeature is stupid and I hate it but I added it because someone begged me to add it (they were too lazy to open wynntils config)

/fuy find exists to check for the world players in /stream because they show up in the api but not with /find (or well this was the case I have no idea if it changed though)

**Comment by kristofbolyai** [comment]
> AttackTimerOverlayFeature relies mostly on the chat for timers and not the scoreboard. This does mean it can be wrong on certain swamp territories (class -> log in -> timer on scoreboard -> guesses the wrong territory) but overall its better. (It can also display more timers; probably too many)
> 
> AutoSkipDialogueFeature is stupid and I hate it but I added it because someone begged me to add it (they were too lazy to open wynntils config)
> 
> /fuy find exists to check for the world players in /stream because they show up in the api but not with /find (or well this was the case I have no idea if it changed though)

Thanks. I wanted to talk to you on Discord, so you had an idea we are doing this, but my time ran out shortly after making this PR.

**Comment by Essentuan** [comment]
nah dont worry its all good

**Comment by kristofbolyai** [comment]
> AttackTimerOverlayFeature relies mostly on the chat for timers and not the scoreboard. This does mean it can be wrong on certain swamp territories (class -> log in -> timer on scoreboard -> guesses the wrong territory) but overall its better. (It can also display more timers; probably too many)

We basically do this as well. We collect the chat messages, and whenever the scoreboard line appears, we match it to the defense. Do you do `startsWith` for the territory name (we do `equals`), so you can guess the full territory name? What if the war was queued with in /class?

**Comment by Essentuan** [comment]
> We basically do this as well. We collect the chat messages, and whenever the scoreboard line appears, we match it to the defense. Do you do `startsWith` for the territory name (we do `equals`), so you can guess the full territory name? What if the war was queued with in /class?

What I mean by relies on chat is it will add the territory as a timer when it sees the message and I parse the message to get the timer duration then display the timer based on that. 

I do check for scoreboard timers but if a known timer (one from chat) starts with the name displayed on the scoreboard it will refuse to add the timer. If thats not the case it'll first check if any territory equals that name otherwise itll resort to `startsWith`.

So yeah if you are in class it can get the territory wrong but I've only seen it happen on the Swamp Dark Forest Transition territories and no ones really complained about it. I think this is the best you can do to keep track of more timers than displayed on the scoreboard without using an external server.

Also on formatting - The normal color for the territory will be gold, however if you're in the territory its bold & magenta. And the defense is italicized if it got the defense from the territory map whereas defenses from chat will not.

**Comment by kristofbolyai** [comment]
Cherry-picked and merged into main.

**Pull request closed without merging**
