### PR TITLE
feat: add a small-map in the caves screen

### PR DESCRIPTION
**Pull request by kristofbolyai**
I am not sure if this should be kept, but I just added this small detail to fill the space.

image

### CODE REVIEW

**Comment by magicus** [comment]
Oh, looks very nice! Maybe also draw the cave icon at the actual cave location?

**Comment by magicus** [comment]
When we fix raids, boss altars, dungeons we can add the map to them as well.

**Review by magicus — APPROVED** [review]

**Comment by kristofbolyai** [comment]
> Oh, looks very nice! Maybe also draw the cave icon at the actual cave location?

I tried it but it looked weird with the icon.

**Comment by magicus** [comment]
Ok

**Pull request merged**
