### PR TITLE
fix: Reintroduced safeCasting

### PR DESCRIPTION
**Pull request by kio7**
As stated in the title, this PR adds safeCasting back into `QuickCastFeature.java`

This functionality has already been requested back by some users in discord. After a week of having to downgrade Wynntils every time i launch MC i got enough and here we are :smile:

### CODE REVIEW

**Comment by kristofbolyai** [comment]
From what I see, this is just a full revert. I don't think that will work for us, although I am not a 100% up to date on all the new rules..

**Comment by kio7** [comment]
It's meant to be a revert, but not a full revert, only parts of #3012 have been reverted.
And what do you mean by new rules?

**Comment by DevChromium** [comment]
Our current implementation of quick casting is in 100% accordance with the new rules. The old version however would've made the feature bannable since it was a bit bugged (added some clicks for no reason).

**Comment by kio7** [comment]
Alright, then ig i'll need to have a look at how to create it without bugs. Ty for the info.

**Comment by ShadowCat117** [comment]
Just fyi I was planning to look into readding safe casting tomorrow but a different way to how we did it before, it would likely be blocking all quick casts until the spell has timed out instead of sending the inputs if the current input was compatible and then you'd have a leftover input

**Comment by kio7** [comment]
Closing this PR as @ShadowCat117 has made a new implementation.

**Pull request closed without merging**
