### PR TITLE
chore: Update the failed to connect messages [skip ci]

### PR DESCRIPTION
**Pull request by ShadowCat117**
image

### CODE REVIEW

**Review by kristofbolyai — COMMENTED** [review]
I think we might as well do "Click __here__(underline) to try to reconnect".

**Comment by ShadowCat117** [comment]
image

**Review by kristofbolyai — APPROVED** [review]
Thanks!

**Comment by magicus** [comment]
I made a review comment but it was apparently not posted due to spotty Internet connection. :( If we're updating this message, I suggest we remove the "Welps!". Is that even a real word? It makes the error message sound not very serious, and do not fit with the rest of the style of our error messages, which are plain and to the point.

**Comment by ShadowCat117** [comment]
I suppose it can be removed, didn't really think that much about it. I won't make a pr just for that change, I'm sure something will be done soon we can bundle it with

**Pull request merged**
