### PR TITLE
feat: Add the name of crafted items to the string shared when sharing encoded items [skip ci]

### PR DESCRIPTION
**Pull request by magicus**
Solves https://github.com/Wynntils/Wynntils/issues/2878.

### CODE REVIEW

**Review by ryanzhoudev — COMMENTED** [review]
Now that #2880 is here, I think we should wait for a consensus on that, or at least make this a config option.

**Comment by kristofbolyai** [comment]
I'll expand this with proper parsing for names in "".

**Comment by magicus** [comment]
I'll push the branch to the Wynntils repo instead of my personal fork, and you can take it over from there.

**Comment by magicus** [comment]
Opened https://github.com/Wynntils/Wynntils/pull/2887 instead.

**Pull request closed without merging**
