### PR TITLE
port: Start using WynntilsCheckbox exclusively (1.21 backport) [skip ci]

### PR DESCRIPTION
**Pull request by kristofbolyai**
This change is easily done, and allows us to not depend on Minecraft's checkbox, which received breaking changes in 1.21 that makes it impractical to use for us.

### CODE REVIEW

**Review by magicus — APPROVED** [review]

**Comment by ShadowCat117** [comment]
The consuming checkbox on chat tabs screen doesn't seem to be toggleable, though that also happens in the current release so not caused by this. Might also be worth extending its max text width as it's scrolling on gui scale 3+ even though there's plenty of room for the text

**Comment by kristofbolyai** [comment]
@ShadowCat117 I fixed the width issue, but I seem to be able to toggle the checkbox.

**Comment by ShadowCat117** [comment]
Hmm for me it makes the clicked sound but doesn't actually update. Does it actually require a valid pattern to update, I don't use chat tabs so don't really know how it works honestly

**Comment by kristofbolyai** [comment]
Hm. I will leave it up to you to fix this then, I have no idea, it works for me. Also, it doesn't really block this PR, so it's fine.

**Pull request merged**
