### PR TITLE
feat: Add new account types [skip ci]

### PR DESCRIPTION
**Pull request by DevScyu**
Add new account types for nametags

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Looks good.

**Comment by kristofbolyai** [comment]
Does this code crash on earlier patches? I hope not..

**Comment by DevScyu** [comment]
I don't know if previous builds will crash if the client encounters a user with a account type that isn't in that enum. But I'm not planning on giving the new account types for a while, just wanted to get the client side out in case it does crash old builds

**Comment by kristofbolyai** [comment]
> I don't know if previous builds will crash if the client encounters a user with a account type that isn't in that enum. But I'm not planning on giving the new account types for a while, just wanted to get the client side out in case it does crash old builds

I'll make sure to check that. In the meantime, let's merge this.

**Pull request merged**
