### PR TITLE
feat: Add /feature reload

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Review by magicus — APPROVED** [review]

**Comment by Incompleteusern** [comment]
`setUserEnabled` should not be set, this is imo a structural flaw. User Enabled should be more of a condition that is set.

**Comment by kristofbolyai** [comment]
> `setUserEnabled` should not be set, this is imo a structural flaw. User Enabled should be more of a condition that is set.

Perhaps. Will fix this tmrw

**Comment by Incompleteusern** [comment]
I think this is actually what the `Condition` system was made for, as a set of predicates that need to be satisfied to enable a feature.

**Comment by kristofbolyai** [comment]
> I think this is actually what the `Condition` system was made for, as a set of predicates that need to be satisfied to enable a feature.

you wanna treat user enabled as a condition? otherwise i am not sure what you are getting at.

**Comment by Incompleteusern** [comment]
> > I think this is actually what the `Condition` system was made for, as a set of predicates that need to be satisfied to enable a feature.
> 
> you wanna treat user enabled as a condition? otherwise i am not sure what you are getting at.

yes if possible

**Comment by magicus** [comment]
I'm slightly worried that the Condition system is overly broad. It seems to bite off more than it can chow, abstraction-wise. Changing a very concrete thing like "user enabled" into a general "condition" seems like a step backwards.

**Pull request merged**
