### PR TITLE
feat: Add a GUI for crowd sourcing settings

### PR DESCRIPTION
**Pull request by kristofbolyai**
I would love to get this in while we are still on 1.19.4. Then I can update the 1.20.2 branch, so we will be ready for 2.0.4, when we will need this.

image
image

### CODE REVIEW

**Comment by ShadowCat117** [comment]
I wonder if we should prompt the user to enable/disable crowd sourcing, like how we currently do for telemetry? Have it on by default, then two options in chat for disable or let me choose what to collect and that will open this screen

**Comment by kristofbolyai** [comment]
> I wonder if we should prompt the user to enable/disable crowd sourcing, like how we do for telemetry? Have it on by default, then two options in chat for disable or let me choose what to collect and that will open this screen

Sure, I can add it

**Comment by kristofbolyai** [comment]
Confirmation messages are now in.

**Review by ShadowCat117 — APPROVED** [review]
Looks good to me

**Pull request merged**
