### PR TITLE
Fix isFoil mixin signature

### PR DESCRIPTION
**Pull request by magicus**

### CODE REVIEW

**Comment by magicus** [comment]
Yes, `B` is not boolean. And there was an argument. Sloppy me. :(

**Review by kristofbolyai — APPROVED** [review]

**Comment by kristofbolyai** [comment]
Are you using auto complete for this kind of work?

**Review by kristofbolyai — APPROVED** [review]

**Comment by magicus** [comment]
No..? The Minecraft IntelliJ plugin validates signatures (sort-of) for me, but I have not gotten it to auto complete. Am I missing something? What I usually do is to check that the signature matches by clicking on the little redirect icon in the gutter. If the signature is correct, it takes me to the corresponding method in Mojangs code.

**Comment by magicus** [comment]
But I'd looove for the Minecraft plugin to have like, you right-click on a method in Minecraft, and select "Create a mixin for this method"...

**Comment by kristofbolyai** [comment]
image

**Comment by kristofbolyai** [comment]
This comes up after CTRL + Space for me.

**Comment by kristofbolyai** [comment]
image

**Comment by magicus** [comment]
Hm, okay, but if you select one of those, do you get the signature as well? I do get the same, but when I select one I only get the method name, and that is kind of trivial... It's the signature that's the PITA.

**Comment by kristofbolyai** [comment]
> Hm, okay, but if you select one of those, do you get the signature as well? I do get the same, but when I select one I only get the method name, and that is kind of trivial... It's the signature that's the PITA.

You get the signature when it is needed. When there is only 1 method with that name, the name is enough in the mixin. When there is a need for full signature, it auto completes that.

**Comment by magicus** [comment]
Hm. I prefer to have the full signature. If that ever changes, I want to have an early failure.

**Pull request merged**
