### PR TITLE
feat: Show item type for chat items, show perfect/defective

### PR DESCRIPTION
**Pull request by kristofbolyai**
image
image

### CODE REVIEW

**Review by ShadowCat117 — APPROVED** [review]
Looks good!

**Comment by magicus** [comment]
I wonder about the use of `makeObfuscated` here. The idea is that it should be used when we have control over the rendering, since each letter has a chance of getting replaced with a weird one. This works okay if they just flicker in and out of existence, but when sent to chat it gets permanent, so if you are unlucky one of the letters disappear and will never re-appear.

Instead I think you should just make defective items bold and dark red.

The rainbow variant is okay. While it will not move, the idea comes across and it will always be visible.

**Comment by kristofbolyai** [comment]
> I wonder about the use of `makeObfuscated` here. The idea is that it should be used when we have control over the rendering, since each letter has a chance of getting replaced with a weird one. This works okay if they just flicker in and out of existence, but when sent to chat it gets permanent, so if you are unlucky one of the letters disappear and will never re-appear.
> 
> 
> 
> Instead I think you should just make defective items bold and dark red.
> 
> 
> 
> The rainbow variant is okay. While it will not move, the idea comes across and it will always be visible.

The chance of obfuscation is 0 here, I just used the bold/red part of the formatting.

**Comment by magicus** [comment]
Ah, I see. Then it is all good! 👍

**Pull request merged**
