### PR TITLE
fix: Fix skill point annotator [skip ci]

### PR DESCRIPTION
**Pull request by ShadowCat117**
image
image

### CODE REVIEW

**Review by ryanzhoudev — APPROVED** [review]
Can you revert the CustomBankPageNamesFeature.java change tho?

**Comment by ShadowCat117** [comment]
I think it's just because spotless wasn't ran on #2627.

I've removed the feature in #2637 anyway and merged it with the new feature

**Review by kristofbolyai — COMMENTED** [review]
Actually, it would be wise to check all uses of À, because it was removed from many places.

**Comment by ShadowCat117** [comment]
> Actually, it would be wise to check all uses of À, because it was removed from many places.

Sure, I can take a look at some

**Pull request merged**
