### PR TITLE
Screens: Add GearViewerScreen

### PR DESCRIPTION
**Pull request by kristofbolyai**
image

### CODE REVIEW

**Comment by kristofbolyai** [comment]
image

**Review by Incompleteusern — APPROVED** [review]
LGTM, I don't assume we do powder related calculations though

**Comment by kristofbolyai** [comment]
> LGTM, I don't assume we do powder related calculations though

Wdym about powders?

**Comment by Incompleteusern** [comment]
> > LGTM, I don't assume we do powder related calculations though
> 
> Wdym about powders?

Assuming this hasn't changed, powders change the amount of ele def/damage for equipment

**Comment by kristofbolyai** [comment]
> > > LGTM, I don't assume we do powder related calculations though
> 
> > 
> 
> > Wdym about powders?
> 
> 
> 
> Assuming this hasn't changed, powders change the amount of ele def/damage for equipment

Oh yeah but that is calculated in gear item stack. I did not change that. I added a new constructor which is basically a modified version of the chat item parser. I assume this is handled some way in gear itemstack.

**Pull request merged**
