### PR TITLE
chore: Don't spam the log with exception stack traces [skip ci]

### PR DESCRIPTION
**Pull request by magicus**
"Fixes" #2560.

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Yeah, sure, this is marginally better. Thanks.

**Comment by magicus** [comment]
"marginally better"?! :-D I thought this was actually good -- you get to see that something happens but the log is not dominated by irrelevant stack traces.

But we really need to fix Athena. Or disable the Athena functionality completely.

**Comment by kristofbolyai** [comment]
> "marginally better"?! :-D I thought this was actually good -- you get to see that something happens but the log is not dominated by irrelevant stack traces.

Some people that doesn't understand it will go and panic, whether they see a 1 line error, or a 10 line one :).

> But we really need to fix Athena. Or disable the Athena functionality completely.

I've been advocating that in Discord for a long time. At this point, I really don't know, what else I can do.

**Comment by ShadowCat117** [comment]
As a side note, the error for failing to connect could be made a little better. The Hades one could mention that friends/party members won't be visible on the map to hopefully get less people asking about that.

And then the account one mentions cloud config syncing won't work, which I assume was just copied from legacy as Artemis doesn't have cloud configs

**Comment by kristofbolyai** [comment]
Agreed, all of those messages are bad, outdated, or both.

**Pull request merged**
