### PR TITLE
Client side commands and /wynntils

### PR DESCRIPTION
**Pull request by kristofbolyai**
This PR adds support for fully functional client side commands (autocomplete, parsing, executing). The PR also adds the first command, `/wynntils` (with limited functionality).

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Also perhaps this could be opened for review and add specific commands in other PRs?

**Comment by kristofbolyai** [comment]
Suggestions do not seem to work: 
image
image

**Comment by kristofbolyai** [comment]
Another problem: 
image

We seem to ignore server commands.

**Comment by kristofbolyai** [comment]
Fixed command suggestions.
image

Server commands are getting sent to server correctly too (`/help` and `/wynntils help`):
image

**Review by Incompleteusern — DISMISSED** [review]

**Review by Incompleteusern — APPROVED** [review]

**Pull request merged**
