### PR TITLE
chore: Update gradle [skip ci]

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by magicus** [comment]
What version of gradle is this? Can you update the PR description to mention that?

**Review by magicus — APPROVED** [review]

**Comment by kristofbolyai** [comment]
> What version of gradle is this? Can you update the PR description to mention that?

I am not exactly sure. It seems like gradle updated itself when I was working on the project. From looking at the diff, it definitely seems as a new gradle version.

**Comment by magicus** [comment]
Eh. I did not thought it could do that? Maybe we should re-do this more controlled. Let me check in my environment.

**Comment by magicus** [comment]
It is supposed to only update this if you run like `gradle wrapper --gradle-version 7.3`.

**Review by magicus — CHANGES_REQUESTED** [review]
Latest version of gradle is 7.6. I think it's better to skip this "what is this I don't even" random change and make a controlled upgrade to 7.6 using the gradle wrapper command.

**Review by magicus — APPROVED** [review]

**Pull request merged**
