### PR TITLE
refactor: compress every image lossless

### PR DESCRIPTION
**Pull request by EnderNon**
In the `common/src/main/resources/assets/wynntils/textures` directory I used the command `oxipng -o max --strip all --alpha **/*.png` (from the utility [oxipng](https://github.com/shssoichiro/oxipng)). The attributes used: 
- `-o max` max compression
- `--strip all` strips as much metadata as possible. There's also a `--strip safe` option that tries to prevent any slightly important metadata being removed, but using the `--strip all` option seemingly hasn't broken anything for me as I tested it.
- `-- alpha` toggles trying to optimize the alpha (opacity), because that will probably break something.

What this has done has reduced the size of the built mod by nearly 10%. According to my file manager, Wynntils v2.3.11 fabric for MC 1.21.1 has a size of 20.5 MiB (21,533,944) while the development build I built using `gradlew buildDependents` has a size of 18.9 MiB (19,815,143). It's also reduced the size of the `textures` directory in the source code by just under 50%, from 3.9 MiB (4,121,709) to 2.2 MiB (2,285,981).

Screenshot showing it's not broken anything (I went into every menu to check but that's too many screenshots)
image

### CODE REVIEW

**Comment by EnderNon** [comment]
[zsh_log.txt](https://github.com/user-attachments/files/17926428/zsh_log.txt)

Here is my log if you want to verify it for some reason

**Comment by EnderNon** [comment]
I forgot to mention that I ran `oxipng -o max --strip all --alpha logo.png` on the logo too as it was out of the textures dir, and for some reason it's made it a bit dimmer. Every other file in the textures dir seems to have no pixel change though.

**Comment by magicus** [comment]
I appreciate the effort. We have done similar stuff for downloadable images (for maps). 

However, this is a one-shot effort. To keep the png files minimized, we need to have a method. Is the oxipng tool idempotent, i.e. if you run it a second time on a file, will it make any changes or not?

I'd like to see a script or a gradle target to run this tool on our images, and not just a one-time update like this.

**Comment by EnderNon** [comment]
> I appreciate the effort. We have done similar stuff for downloadable images (for maps).
> 
> However, this is a one-shot effort. To keep the png files minimized, we need to have a method. Is the oxipng tool idempotent, i.e. if you run it a second time on a file, will it make any changes or not?
> 
> I'd like to see a script or a gradle target to run this tool on our images, and not just a one-time update like this.

I ran the oxipng tool again once, and it showed some changes here: [zsh_history_2.txt](https://github.com/user-attachments/files/17926665/zsh_history_2.txt). After that, no more changes were found, after rerunning the tool multiple times, so I've committed them. I'm not sure why it didn't pick up on any possible changes when I ran it when creating this PR, but the rerun found any new changes.

Each time, I've run the tool in `common/src/main/resources/assets/wynntils/textures` . I'm not actually sure how to make gradle run a script, but a shell script would be as follows (assuming your current dir is the root of git repo):


```
cd ./common/src/main/resources/assets/wynntils/textures
oxipng -o max --strip all --alpha **/*.png
oxipng -o max --strip all --alpha **/*.png
```

edit: here's the log after it shows there's no more changes to be made: 
[zsh_history_3.txt](https://github.com/user-attachments/files/17926689/zsh_history_3.txt)

Edit 2: Also, I'm not actually sure what environment gradle is running in, but there are different methods for obtaining oxipng depending on your linux distribution or OS (see [this](https://github.com/shssoichiro/oxipng?tab=readme-ov-file#installing)). It's also available through cargo but including cargo in the build files for a java project just for one thing seems rather strange.

**Comment by kristofbolyai** [comment]
Honestly, I am a bit skeptical here, the file size change is in the KBs, so overall, it would have a really small effect on the end file. Considering the mod itself doesn't have to be downloaded that frequently, and that it is not that sensitive to download failure, we might not need the optimization afterall. However, if you can get it working nicely with Github CI/Gradle, I am fine to accept it.

**Comment by kristofbolyai** [comment]
Honestly, I am a bit skeptical here, the file size change is in the KBs, so overall, it would have a really small effect on the end file. Considering the mod itself doesn't have to be downloaded that frequently, and that it is not that sensitive to download failure, we might not need the optimization afterall. However, if you can get it working nicely with Github CI/Gradle, I am fine to accept it.

**Comment by EnderNon** [comment]
> Honestly, I am a bit skeptical here, the file size change is in the KBs, so overall, it would have a really small effect on the end file. Considering the mod itself doesn't have to be downloaded that frequently, and that it is not that sensitive to download failure, we might not need the optimization afterall. However, if you can get it working nicely with Github CI/Gradle, I am fine to accept it.

You're right about how it likely won't be that big of a deal. I'm going to try and do it like this
- Detect the operating system of whoever is trying to build
- download a specified precompiled version of latest oxipng from their github releases
- Run oxipng in the `textures` directory, and pass the correct arguments

Though it seems really excessive and honestly not all worth it, because I don't actually know how to use gradle or github ci.

**Comment by EnderNon** [comment]
yeah ok i can't figure it out at all

**Comment by derNiklaas** [comment]
Wouldn't this do sth similar? https://github.com/apps/imgbot

**Comment by magicus** [comment]
FWIW, https://github.com/simonw/til/blob/main/github-actions/oxipng.md

**Comment by EnderNon** [comment]
> FWIW, https://github.com/simonw/til/blob/main/github-actions/oxipng.md


image
that's cool. Can you change directories in Github Actions? If so, then it might be feasible to run this.

**Comment by EnderNon** [comment]
Well, I was using this fork for something else as a test :/

Is it possible for you to discard these commits that just got added?

**Comment by kristofbolyai** [comment]
I'll close this PR as I don't think the benefits are worth the hassle. If you can get some additional gains, we may be interested in that, please open an issue to discuss, if that's the case.

**Pull request closed without merging**
