### PR TITLE
chore: Update url md5 for major ID file

### PR DESCRIPTION
**Pull request by P0keDev**
Requires https://github.com/Wynntils/WynntilsWebsite-API/pull/127 to be merged first

### CODE REVIEW

**Review by magicus — APPROVED** [review]

**Comment by magicus** [comment]
I'd like to point out (to @kristofbolyai too) that updating the artemis md5 is not a strict requirement. What will happen when we update the API site is that at next startup, the clients will download the new urls.json from there, and use it instead of the bundled one. The updated md5 in this file is only useful in the very weird scenario where a client has downloaded the updated major_ids.json file, but has lost their downloaded urls.json, and somehow cannot re-download from the API site again (due to github outage, or the Great Firewall of China). Then Artemis will consider the downloaded major_ids.json to be invalid and remove it.

**Comment by magicus** [comment]
Of course we can keep updating it like this, but we can also make a bulk update from the API copy every once in a while.

**Comment by kristofbolyai** [comment]
@magicus the best would be automatic PRs, with [ci skip] so its in the next build

**Comment by magicus** [comment]
Yeah, but how..? Maybe add a GHA cron job to Artemis that pulls urls.json from the API site? Like how we do with gears from Wynn API. I could probably do that.

**Comment by magicus** [comment]
Proposed solution in #1982

**Pull request merged**
