### PR TITLE
refactor: Models need intra-model dependencies

### PR DESCRIPTION
**Pull request by magicus**
Just as with Managers, Models can depend on Models and thus initialization order must be correct. (This will be needed in upcoming item tooltip changes.)

### CODE REVIEW

**Comment by magicus** [comment]
Also, we might want to look over our design as well. Some of these dependencies look strange. At least these comes to mind:

```
    public static final LootChestModel LootChest = new LootChestModel(Container);
    public static final LootrunModel Lootrun = new LootrunModel(Container);
    public static final MapModel Map = new MapModel(GuildAttackTimer);
    public static final PlayerRelationsModel PlayerRelations = new PlayerRelationsModel(WorldState);
    public static final QuestModel Quest = new QuestModel(Character);
    public static final ShamanMaskModel ShamanMask = new ShamanMaskModel(WorldState);
    public static final ShamanTotemModel ShamanTotem = new ShamanTotemModel(WorldState);
    public static final DiscoveryModel Discovery = new DiscoveryModel(Character, Compass, Quest, Territory);
    public static final EmeraldModel Emerald = new EmeraldModel(Item);
```

**Review by kristofbolyai — APPROVED** [review]
I thought we had these.. Or was it managers..?

**Comment by magicus** [comment]
@kristofbolyai It was just for managers.
In the old world, the dependency was upheld by a feature A that needed model X, and if model X needed model Y, then feature A said it depended on both X and Y. (So it had to know intimate details about models). 

I have in generally tried to remove inter-model dependencies. I realize we can't get rid of them entirely, but we should try to minimize them. (As with Managers)

**Comment by kristofbolyai** [comment]
I see now, thanks!

**Pull request merged**
