### PR TITLE
Add invisible player transparency setting

### PR DESCRIPTION
**Pull request by Incompleteusern**
If the player is invisible due to something such vanish, they can be rendered translucently instead

### CODE REVIEW

**Comment by magicus** [comment]
That sounds like a cheat. Is this available in Legacy? You need to verify with Wynncraft if that is really allowed.

**Review by magicus — CHANGES_REQUESTED** [review]
Do not integrate until the permissibility is sorted out.

**Comment by Incompleteusern** [comment]
> That sounds like a cheat. Is this available in Legacy? You need to verify with Wynncraft if that is really allowed.

It's only the actual player, and not any other players/party members, which should be acceptable. Will ask nonetheless.

**Comment by magicus** [comment]
It changes the cost of doing vanish significantly.

**Comment by Incompleteusern** [comment]
> It changes the cost of doing vanish significantly.

I've asked in the channel

**Comment by Incompleteusern** [comment]
Apparently this is already in the game

**Pull request closed without merging**
