### PR TITLE
feat: Wynntils item functionality will now work in Trade Market

### PR DESCRIPTION
**Pull request by magicus**
Make a more lax name matching, and only extract name once, to match item names in Trade Market as well

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Is this optimization, or what does this do?

**Comment by magicus** [comment]
It is mostly a fix/feature, but also an optimization. :-)

Trade Market names have these weird `À` character in the name. We need to strip them out to match. This was just done for a few stacks before (matching where it was done with the old framework). So it is a fix/feature to have this work for all items.

The optimization is that we extract and normalize the name string once for each item, and not have every annotator do that. The code gets cleaner, and there is no risk we forget to normalize.

**Review by kristofbolyai — APPROVED** [review]
LGTM although PR title is a bit confusing

**Comment by magicus** [comment]
I tried to write the PR title so it would make sense in the changelog. Apparently I failed. :) Hope this was better.

**Pull request merged**
