### PR TITLE
feat: Auto message territory defense on attack

### PR DESCRIPTION
**Pull request by kristofbolyai**
image

### CODE REVIEW

**Review by Incompleteusern — CHANGES_REQUESTED** [review]
We should ask wynncraft moderators if we can even automate message sending in this capacity

**Comment by kristofbolyai** [comment]
> We should ask wynncraft moderators if we can even automate message sending in this capacity

avomod does this so

**Comment by Incompleteusern** [comment]
> > We should ask wynncraft moderators if we can even automate message sending in this capacity
> 
> avomod does this so

I'd rather we still ask and be safe than sorry.

**Review by Incompleteusern — APPROVED** [review]
Still feel it could be a bit more obvious we are automating, but is fine

**Pull request merged**
