### PR TITLE
Features: Add custom nametag rendering

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
image

**Review by Incompleteusern — APPROVED** [review]
LGTM, though rainbow text rendering doesn't exist yet.

**Comment by HighCrit** [comment]
I don't know whether we'd want to add it here. But I had an ambition to implement a structure like the following inside cosmetics 
```json
//Cosmetics 
"title": {
  "value": "Destroyer of Worlds",
  "color": 0 //any color format we choose
}
```

**Comment by kristofbolyai** [comment]
> I don't know whether we'd want to add it here. But I had an ambition to implement a structure like the following inside cosmetics 
> 
> ```json
> 
> //Cosmetics 
> 
> "title": {
> 
>   "value": "Destroyer of Worlds",
> 
>   "color": 0 //any color format we choose
> 
> }
> 
> ```
> 
>     

How would this appear?

**Comment by HighCrit** [comment]
> How would this appear?
It would be a way to support custom titles as cosmetics for special people or occasions

**Pull request merged**
