### PR TITLE
fix: Fix tomes being counted as defective, if they had no identifications [skip ci]

### PR DESCRIPTION
**Pull request by ShadowCat117**

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Can you check the charm implementation..? I did this for gears already, but I think that one is still missing.

**Comment by ShadowCat117** [comment]
Charms all have ids so they shouldn't need it

**Comment by kristofbolyai** [comment]
> Charms all have ids so they shouldn't need it

The code should get fixed anyways.

**Comment by ShadowCat117** [comment]
https://github.com/Wynntils/Artemis/pull/2530

**Pull request merged**
