### PR TITLE
refactor: Turn WynnPlayerUtils into PlayerRank enum

### PR DESCRIPTION
**Pull request by magicus**

### CODE REVIEW

**Review by kristofbolyai — APPROVED** [review]
Nice refactor. Did you start fixing the regex for this..?

**Comment by magicus** [comment]
No..? I just looked through utils to see if there were anything that perhaps should be moved to services.

**Comment by magicus** [comment]
I have been trying to keep a strict regime to keep "model" stuff out of utils (I have a thorn in the side for InventoryUtils and WynnItemMatchers, and some day I'm gonna fix them), but services has had no real place to go, so I thought there would be such. I did not find any, but I found this.

**Comment by kristofbolyai** [comment]
> No..? I just looked through utils to see if there were anything that perhaps should be moved to services.

Oh.. This feature is broken atm pending a regex fix for 2.0.3, I thought you found this by fixing it...

**Pull request merged**
