### PR TITLE
Bump version of artemis

### PR DESCRIPTION
**Pull request by DevScyu**
Since this version is a massive breaking change from previous wynntils, we should version it as such.

Wynntils 2.0 let's go!

### CODE REVIEW

**Comment by xcfrg** [comment]
LGTM :rocket:

**Review by Incompleteusern — APPROVED** [review]

**Review by kristofbolyai — APPROVED** [review]
Ok by me, but let's see if everyone is on the same page.

**Comment by DevChromium** [comment]
i very much agree

**Comment by HighCrit** [comment]
I agree

**Review by HighCrit — APPROVED** [review]

**Comment by magicus** [comment]
Does this version mean “version of Wynntils” or “version of Artemis”? I’m not sure it makes sense to consider it the former. 

In any case I don’t think we’re anyway near a proper release that needs a real version number. 

Sure, you can set it to 2.0, but what does it *mean*? Is it helpful?

**Comment by DevScyu** [comment]
> Does this version mean “version of Wynntils” or “version of Artemis”? I’m not sure it makes sense to consider it the former.
> 
> In any case I don’t think we’re anyway near a proper release that needs a real version number.
> 
> Sure, you can set it to 2.0, but what does it _mean_? Is it helpful?

Just helps when people are asking for support if they see 2.0, also since we're building this now, it should also work for wynn 2.0

**Comment by P0keDev** [comment]
personally, i don't think we should be offering support for artemis yet, or posturing as such with a version change (especially since it corresponds to no actual changes/wynn 2.0 compatibility updates?)

the mod as-is functions as a lightweight enhancement for wynncraft, but it hardly serves as a replacement to the wynntils people know, and many of its features are experimental or not complete

**Comment by magicus** [comment]
@P0keDev Agree 💯

**Comment by HighCrit** [comment]
Well Artemis is supposed to eventually become Wynntils. So I'd say bumping the major version is okay. But I do not have a preference for when, so perhaps when Artemis actually replaces Wynntils?

**Comment by magicus** [comment]
I think we might have a bit of communication story to think through when we are ready to publicly support Artemis. Should we just call it Wynntils 2? Or should we rename the old mod "Wynntils Legacy" or "Wynntils Classic"? How should we do versioning? Perhaps using a <year>.<month> style, or a tradititional semver, or a modern fast increasing dotless version number like Firefox and the JDK.

But it is waaaaay to early to have that discussion now. We don't have anything that even remotely resembles the classic Wynntils mod.

**Comment by xcfrg** [comment]
This is a code base completely unrelated to 1.12.2 Wynntils, so *technically* this should be 1.x.x

**Pull request closed without merging**
